//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCDocDedRed", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcDocDedRed
    {
        
        /// <summary>
        /// <para>Chave de Acesso da NFS-e (Padrão Nacional)</para>
        /// <para>Tipo Chave da Nota Fiscal de Serviço Eletrônica</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// <para xml:lang="en">Pattern: [0-9]{50}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Chave de Acesso da NFS-e (Padrão Nacional)")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{50}")]
        [System.Xml.Serialization.XmlElementAttribute("chNFSe")]
        public string ChNfSe { get; set; }
        
        /// <summary>
        /// <para>Chave de Acesso da NF-e</para>
        /// <para>Tipo Chave da Nota Fiscal Eletrônica - NF-e</para>
        /// <para xml:lang="en">Maximum length: 44.</para>
        /// <para xml:lang="en">Pattern: [0-9]{44}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Chave de Acesso da NF-e")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(44)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{44}")]
        [System.Xml.Serialization.XmlElementAttribute("chNFe")]
        public string ChNFe { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações de Outras NFS-e (Padrão anterior de NFS-e)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações de Outras NFS-e (Padrão anterior de NFS-e)")]
        [System.Xml.Serialization.XmlElementAttribute("NFSeMun")]
        public TcDocOutNfSe NfSeMun { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações de NF ou NFS (Modelo não eletrônico)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações de NF ou NFS (Modelo não eletrônico)")]
        [System.Xml.Serialization.XmlElementAttribute("NFNFS")]
        public TcDocNfnfs Nfnfs { get; set; }
        
        /// <summary>
        /// <para>Número de documento fiscal</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número de documento fiscal")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("nDocFisc")]
        public string NDocFisc { get; set; }
        
        /// <summary>
        /// <para>Número de documento não fiscal</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número de documento não fiscal")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("nDoc")]
        public string NDoc { get; set; }
        
        /// <summary>
        /// <para>Identificação da Dedução/Redução:
        ///            1 – Alimentação e bebidas/frigobar;
        ///            2 – Materiais;
        ///            5 – Repasse consorciado;
        ///            6 – Repasse plano de saúde;
        ///            7 – Serviços;
        ///            8 – Subempreitada de mão de obra;
        ///            99 – Outras deduções;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Identificação da Dedução/Redução: 1 – Alimentação e bebidas/frigobar; 2 – Materia" +
            "is; 5 – Repasse consorciado; 6 – Repasse plano de saúde; 7 – Serviços; 8 – Subem" +
            "preitada de mão de obra; 99 – Outras deduções;"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("tpDedRed")]
        public TsIdeDedRed TpDedRed { get; set; }
        
        /// <summary>
        /// <para>Descrição da Dedução/Redução quando a opção é "99 – Outras Deduções"</para>
        /// <para>Descrição da Dedução/Redução quando a opção é "99 – Outras Deduções"</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 150.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Descrição da Dedução/Redução quando a opção é \"99 – Outras Deduções\"")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(150)]
        [System.Xml.Serialization.XmlElementAttribute("xDescOutDed")]
        public string XDescOutDed { get; set; }
        
        /// <summary>
        /// <para>Data da emissão do documento dedutível. Ano, mês e dia (AAAA-MM-DD)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data da emissão do documento dedutível. Ano, mês e dia (AAAA-MM-DD)")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dtEmiDoc", DataType="date")]
        public System.DateTime DtEmiDoc { get; set; }
        
        /// <summary>
        /// <para>Valor monetário total dedutível/redutível no documento informado (R$).
        ///            Este é o valor total no documento informado que é passível de dedução/redução.</para>
        /// <para>Valor decimal com 1 a 15 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Valor monetário total dedutível/redutível no documento informado (R$). Este é o v" +
            "alor total no documento informado que é passível de dedução/redução."))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\\.[0-9]{2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("vDedutivelRedutivel")]
        public string VDedutivelRedutivel { get; set; }
        
        /// <summary>
        /// <para>Valor monetário utilizado para dedução/redução do valor do serviço da NFS-e que está sendo emitida (R$).
        ///            Deve ser menor ou igual ao valor deduzível/redutível (vDedutivelRedutivel).</para>
        /// <para>Valor decimal com 1 a 15 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Valor monetário utilizado para dedução/redução do valor do serviço da NFS-e que e" +
            "stá sendo emitida (R$). Deve ser menor ou igual ao valor deduzível/redutível (vD" +
            "edutivelRedutivel)."))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\\.[0-9]{2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("vDeducaoReducao")]
        public string VDeducaoReducao { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações do Fornecedor em Deduções de Serviços</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações do Fornecedor em Deduções de Serviços")]
        [System.Xml.Serialization.XmlElementAttribute("fornec")]
        public TcInfoPessoa Fornec { get; set; }
    }
}
