//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCExigSuspensa", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcExigSuspensa
    {
        
        /// <summary>
        /// <para>Opção para Exigibilidade Suspensa:
        ///            1 - Exigibilidade Suspensa por Decisão Judicial;
        ///            2 - Exigibilidade Suspensa por Processo Administrativo;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Opção para Exigibilidade Suspensa: 1 - Exigibilidade Suspensa por Decisão Judicia" +
            "l; 2 - Exigibilidade Suspensa por Processo Administrativo;"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("tpSusp")]
        public TsOpExigSuspensa TpSusp { get; set; }
        
        /// <summary>
        /// <para>Número do processo judicial ou administrativo de suspensão da exigibilidade</para>
        /// <para>Número do processo judicial ou administrativo de suspensão da exigibilidade</para>
        /// <para xml:lang="en">Pattern: [0-9]{30}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número do processo judicial ou administrativo de suspensão da exigibilidade")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{30}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("nProcesso")]
        public string NProcesso { get; set; }
    }
}
