//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCRTCTotalCIBS", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcrtcTotalCibs
    {
        
        /// <summary>
        /// <para>Valor Total da NF considerando os impostos por fora: IBS e CBS
        ///            O IBS e a CBS são por fora, por isso seus valores devem ser adicionados ao valor total da NF
        ///            vTotNF = vLiq (em 2026)
        ///            vTotNF = vLiq + vCBS + vIBSTot (a partir de 2027)</para>
        /// <para>Valor decimal com 1 a 15 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Valor Total da NF considerando os impostos por fora: IBS e CBS O IBS e a CBS são " +
            "por fora, por isso seus valores devem ser adicionados ao valor total da NF vTotN" +
            "F = vLiq (em 2026) vTotNF = vLiq + vCBS + vIBSTot (a partir de 2027)"))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\\.[0-9]{2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("vTotNF")]
        public string VTotNf { get; set; }
        
        /// <summary>
        /// <para>Grupo de valores referentes ao IBS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de valores referentes ao IBS")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("gIBS")]
        public TcrtcTotalIbs Gibs { get; set; }
        
        /// <summary>
        /// <para>Grupo de valores referentes à CBS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de valores referentes à CBS")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("gCBS")]
        public TcrtcTotalCbs Gcbs { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações de tributação regular</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações de tributação regular")]
        [System.Xml.Serialization.XmlElementAttribute("gTribRegular")]
        public TcrtcTotalTribRegular GTribRegular { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações da composição do valor do IBS e da CBS em compras governamentais</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Grupo de informações da composição do valor do IBS e da CBS em compras governamen" +
            "tais"))]
        [System.Xml.Serialization.XmlElementAttribute("gTribCompraGov")]
        public TcrtcTotalTribCompraGov GTribCompraGov { get; set; }
    }
}
