//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TE205208", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Te205208
    {
        
        /// <summary>
        /// <para>Descrição do evento: "Manifestação de NFS-e - Anulação da Rejeição".</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Descrição do evento: \"Manifestação de NFS-e - Anulação da Rejeição\".")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("xDesc")]
        public Te205208XDesc XDesc { get; set; }
        
        /// <summary>
        /// <para>CPF do agente da administração tributária municipal que efetuou o anulação da manifestação de rejeição da NFS-e</para>
        /// <para>Tipo Número do CPF</para>
        /// <para xml:lang="en">Maximum length: 11.</para>
        /// <para xml:lang="en">Pattern: [0-9]{11}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("CPF do agente da administração tributária municipal que efetuou o anulação da manifestação de rejeição da NFS-e")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{11}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CPFAgTrib")]
        public string CpfAgTrib { get; set; }
        
        /// <summary>
        /// <para>Referência ao "id" do Evento de Manifestação de NFS-e - Rejeição, que originou o presente evento de anulação</para>
        /// <para xml:lang="en">Pattern: [0-9]{59}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Referência ao \"id\" do Evento de Manifestação de NFS-e - Rejeição, que originou o presente evento de anulação")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{59}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("idEvManifRej")]
        public string IdEvManifRej { get; set; }
        
        /// <summary>
        /// <para>Descrição para explicitar o motivo indicado neste evento</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Descrição para explicitar o motivo indicado neste evento")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xMotivo")]
        public string XMotivo { get; set; }
    }
}
