//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TE203206", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Te203206
    {
        
        /// <summary>
        /// <para>Descrição do evento: "Manifestação de NFS-e - Rejeição do Tomador".</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Descrição do evento: \"Manifestação de NFS-e - Rejeição do Tomador\".")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("xDesc")]
        public Te203206XDesc XDesc { get; set; }
        
        /// <summary>
        /// <para>Motivo da Rejeição da NFS-e:
        ///            1 - NFS-e em duplicidade;
        ///            2 - NFS-e já emitida pelo tomador;
        ///            3 - Não ocorrência do fato gerador;
        ///            4 - Erro quanto a responsabilidade tributária;
        ///            5 - Erro quanto ao valor do serviço, valor das deduções ou serviço prestado ou data do fato gerador;
        ///            9 - Outros;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Motivo da Rejeição da NFS-e: 1 - NFS-e em duplicidade; 2 - NFS-e já emitida pelo tomador; 3 - Não ocorrência do fato gerador; 4 - Erro quanto a responsabilidade tributária; 5 - Erro quanto ao valor do serviço, valor das deduções ou serviço prestado ou data do fato gerador; 9 - Outros;")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cMotivo")]
        public TsCodMotivoRejeicao CMotivo { get; set; }
        
        /// <summary>
        /// <para>Descrição para explicitar o motivo indicado neste evento</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Descrição para explicitar o motivo indicado neste evento")]
        [System.Xml.Serialization.XmlElementAttribute("xMotivo")]
        public string XMotivo { get; set; }
    }
}
