//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    /// <summary>
    /// <para>Código do motivo da solicitação de análise fiscal para cancelamento de NFS-e:
    ///        1 - Erro na Emissão;
    ///        2 - Serviço não Prestado;
    ///        3 - Outros.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Código do motivo da solicitação de análise fiscal para cancelamento de NFS-e: 1 -" +
        " Erro na Emissão; 2 - Serviço não Prestado; 3 - Outros."))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TSCodJustAnaliseFiscalCanc", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public enum TsCodJustAnaliseFiscalCanc
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
    }
}
