//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    /// <summary>
    /// <para>Situação perante o Simples Nacional:
    ///        1 - Não Optante;
    ///        2 - Optante - Microempreendedor Individual (MEI);
    ///        3 - Optante - Microempresa ou Empresa de Pequeno Porte (ME/EPP);</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Situação perante o Simples Nacional: 1 - Não Optante; 2 - Optante - Microempreend" +
        "edor Individual (MEI); 3 - Optante - Microempresa ou Empresa de Pequeno Porte (M" +
        "E/EPP);"))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TSOpSimpNac", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public enum TsOpSimpNac
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
}
