//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("cabecalho", Namespace="http://www.sped.fazenda.gov.br/nfse", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("cabecalho", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public partial class Cabecalho
    {
        
        /// <summary>
        /// <para>Tipo Versão da NF-e - 1.01</para>
        /// <para xml:lang="en">Pattern: 1\.01.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("1\\.01")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("versaoDados")]
        public string VersaoDados { get; set; }
        
        /// <summary>
        /// <para>Tipo Versão da NF-e - 1.01</para>
        /// <para xml:lang="en">Pattern: 1\.01.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("1\\.01")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("versao")]
        public string Versao { get; set; }
    }
}
