//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ConsultarLoteDpsResposta", Namespace="http://www.sped.fazenda.gov.br/nfse", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ConsultarLoteDpsResposta", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public partial class ConsultarLoteDpsResposta
    {
        
        /// <summary>
        /// <para>Situação do lote de DPS
        ///          1 – Não Recebido;
        ///          2 – Não Processado;
        ///          3 – Processado com Erro;
        ///          4 – Processado com Sucesso.</para>
        /// <para xml:lang="en">Pattern: 1|2|3|4.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("1|2|3|4")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Situacao")]
        public sbyte Situacao { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ListaNfse")]
        public ConsultarLoteDpsRespostaListaNfse ListaNfse { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TcMensagemRetorno> _listaMensagemRetorno;
        
        [System.Xml.Serialization.XmlArrayAttribute("ListaMensagemRetorno")]
        [System.Xml.Serialization.XmlArrayItemAttribute("MensagemRetorno", Namespace="http://www.sped.fazenda.gov.br/nfse")]
        public System.Collections.ObjectModel.Collection<TcMensagemRetorno> ListaMensagemRetorno
        {
            get
            {
                return _listaMensagemRetorno;
            }
            private set
            {
                _listaMensagemRetorno = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ListaMensagemRetorno collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListaMensagemRetornoSpecified
        {
            get
            {
                return (this.ListaMensagemRetorno.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ConsultarLoteDpsResposta" /> class.</para>
        /// </summary>
        public ConsultarLoteDpsResposta()
        {
            this._listaMensagemRetorno = new System.Collections.ObjectModel.Collection<TcMensagemRetorno>();
            this._listaMensagemRetornoLote = new System.Collections.ObjectModel.Collection<TcMensagemRetornoLote>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TcMensagemRetornoLote> _listaMensagemRetornoLote;
        
        [System.Xml.Serialization.XmlArrayAttribute("ListaMensagemRetornoLote")]
        [System.Xml.Serialization.XmlArrayItemAttribute("MensagemRetorno", Namespace="http://www.sped.fazenda.gov.br/nfse")]
        public System.Collections.ObjectModel.Collection<TcMensagemRetornoLote> ListaMensagemRetornoLote
        {
            get
            {
                return _listaMensagemRetornoLote;
            }
            private set
            {
                _listaMensagemRetornoLote = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ListaMensagemRetornoLote collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListaMensagemRetornoLoteSpecified
        {
            get
            {
                return (this.ListaMensagemRetornoLote.Count != 0);
            }
        }
    }
}
