//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ConsultarNfseFaixaRespostaListaNfse", Namespace="http://www.sped.fazenda.gov.br/nfse", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarNfseFaixaRespostaListaNfse
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TcCompNfse> _compNfse;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CompNfse")]
        public System.Collections.ObjectModel.Collection<TcCompNfse> CompNfse
        {
            get
            {
                return _compNfse;
            }
            private set
            {
                _compNfse = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ConsultarNfseFaixaRespostaListaNfse" /> class.</para>
        /// </summary>
        public ConsultarNfseFaixaRespostaListaNfse()
        {
            this._compNfse = new System.Collections.ObjectModel.Collection<TcCompNfse>();
        }
        
        /// <summary>
        /// <para>Número com 7 dígitos</para>
        /// <para xml:lang="en">Maximum length: 7.</para>
        /// <para xml:lang="en">Pattern: [0-9]{7}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(7)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{7}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Pagina")]
        public string Pagina { get; set; }
    }
}
