//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ConsultarLoteDpsRespostaListaNfse", Namespace="http://www.sped.fazenda.gov.br/nfse", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarLoteDpsRespostaListaNfse
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TcCompNfse> _compNfse;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CompNfse")]
        public System.Collections.ObjectModel.Collection<TcCompNfse> CompNfse
        {
            get
            {
                return _compNfse;
            }
            private set
            {
                _compNfse = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ConsultarLoteDpsRespostaListaNfse" /> class.</para>
        /// </summary>
        public ConsultarLoteDpsRespostaListaNfse()
        {
            this._compNfse = new System.Collections.ObjectModel.Collection<TcCompNfse>();
            this._listaMensagemAlertaRetorno = new System.Collections.ObjectModel.Collection<TcMensagemRetorno>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TcMensagemRetorno> _listaMensagemAlertaRetorno;
        
        [System.Xml.Serialization.XmlArrayAttribute("ListaMensagemAlertaRetorno")]
        [System.Xml.Serialization.XmlArrayItemAttribute("MensagemRetorno", Namespace="http://www.sped.fazenda.gov.br/nfse")]
        public System.Collections.ObjectModel.Collection<TcMensagemRetorno> ListaMensagemAlertaRetorno
        {
            get
            {
                return _listaMensagemAlertaRetorno;
            }
            private set
            {
                _listaMensagemAlertaRetorno = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ListaMensagemAlertaRetorno collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListaMensagemAlertaRetornoSpecified
        {
            get
            {
                return (this.ListaMensagemAlertaRetorno.Count != 0);
            }
        }
    }
}
