//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ConsultarNfseServicoPrestadoEnvio", Namespace="http://www.sped.fazenda.gov.br/nfse", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ConsultarNfseServicoPrestadoEnvio", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public partial class ConsultarNfseServicoPrestadoEnvio
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Prestador")]
        public TcIdentificacaoPessoaEmpresa Prestador { get; set; }
        
        /// <summary>
        /// <para>Tipo Número sequencial do documento</para>
        /// <para xml:lang="en">Maximum length: 13.</para>
        /// <para xml:lang="en">Pattern: [1-9]{1}[0-9]{0,12}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(13)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]{1}[0-9]{0,12}")]
        [System.Xml.Serialization.XmlElementAttribute("NumeroNfse")]
        public string NumeroNfse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PeriodoEmissao")]
        public ConsultarNfseServicoPrestadoEnvioPeriodoEmissao PeriodoEmissao { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PeriodoCompetencia")]
        public ConsultarNfseServicoPrestadoEnvioPeriodoCompetencia PeriodoCompetencia { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Tomador")]
        public TcIdentificacaoPessoaEmpresa Tomador { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Intermediario")]
        public TcIdentificacaoPessoaEmpresa Intermediario { get; set; }
        
        /// <summary>
        /// <para>Número com 7 dígitos</para>
        /// <para xml:lang="en">Maximum length: 7.</para>
        /// <para xml:lang="en">Pattern: [0-9]{7}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(7)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{7}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Pagina")]
        public string Pagina { get; set; }
    }
}
