//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DSAKeyValueType", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("DSAKeyValue", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class DsaKeyValueType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("P", DataType="base64Binary")]
        public byte[] P { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Q", DataType="base64Binary")]
        public byte[] Q { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("G", DataType="base64Binary")]
        public byte[] G { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Y", DataType="base64Binary")]
        public byte[] Y { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("J", DataType="base64Binary")]
        public byte[] J { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Seed", DataType="base64Binary")]
        public byte[] Seed { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PgenCounter", DataType="base64Binary")]
        public byte[] PgenCounter { get; set; }
    }
}
