//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    /// <summary>
    /// <para>Tipo Benefício Municipal (BM):
    ///        1) Isenção;
    ///        2) Redução da BC em 'ppBM' %;
    ///        3) Redução da BC em R$ 'vInfoBM';
    ///        4) Alíquota Diferenciada de 'aliqDifBM' %;</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Tipo Benefício Municipal (BM): 1) Isenção; 2) Redução da BC em \'ppBM\' %; 3) Reduç" +
        "ão da BC em R$ \'vInfoBM\'; 4) Alíquota Diferenciada de \'aliqDifBM\' %;"))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TBMISSQN", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public enum Tbmissqn
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
}
