//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCAtvEvento", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcAtvEvento
    {
        
        /// <summary>
        /// <para>Descrição do evento Artístico, Cultural, Esportivo, etc</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Descrição do evento Artístico, Cultural, Esportivo, etc")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xNome")]
        public string XNome { get; set; }
        
        /// <summary>
        /// <para>Data de início da atividade de evento. Ano, Mês e Dia (AAAA-MM-DD)</para>
        /// <para>Tipo data no formato AAAA-MM-DD</para>
        /// <para xml:lang="en">Pattern: (((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30))))).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data de início da atividade de evento. Ano, Mês e Dia (AAAA-MM-DD)")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute(("(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-" +
            "((0[1-9])|(1\\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29" +
            "|30)))))"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dtIni")]
        public string DtIni { get; set; }
        
        /// <summary>
        /// <para>Data de fim da atividade de evento. Ano, Mês e Dia (AAAA-MM-DD)</para>
        /// <para>Tipo data no formato AAAA-MM-DD</para>
        /// <para xml:lang="en">Pattern: (((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30))))).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data de fim da atividade de evento. Ano, Mês e Dia (AAAA-MM-DD)")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute(("(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-" +
            "((0[1-9])|(1\\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29" +
            "|30)))))"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dtFim")]
        public string DtFim { get; set; }
        
        /// <summary>
        /// <para>Identificação da Atividade de Evento (código identificador de evento determinado pela Administração Tributária Municipal)</para>
        /// <para>Identificação da Atividade de Evento (código identificador de evento determinado pela Administração Tributária Municipal)</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Identificação da Atividade de Evento (código identificador de evento determinado " +
            "pela Administração Tributária Municipal)"))]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.Xml.Serialization.XmlElementAttribute("idAtvEvt")]
        public string IdAtvEvt { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações relativas ao endereço da atividade, evento ou local do serviço prestado</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Grupo de informações relativas ao endereço da atividade, evento ou local do servi" +
            "ço prestado"))]
        [System.Xml.Serialization.XmlElementAttribute("end")]
        public TcEnderecoSimples End { get; set; }
    }
}
