//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCCServ", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TccServ
    {
        
        /// <summary>
        /// <para>Código de tributação nacional do ISSQN, nos termos da LC 116/2003, conforme aba MUN.INCID_INFO.SERV. do ANEXO I
        ///            Regra de formação - 6 dígitos numéricos sendo: 2 para Item (LC 116/2003), 2 para Subitem (LC 116/2003) e 2 para Desdobro Nacional</para>
        /// <para>Código de tributação nacional do ISSQN:
        ///        Regra de formação - 6 dígitos numéricos sendo: 2 para Item (LC 116/2003), 2 para Subitem (LC 116/2003) e 2 para Desdobro Nacional</para>
        /// <para xml:lang="en">Pattern: [0-9]{6}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Código de tributação nacional do ISSQN, nos termos da LC 116/2003, conforme aba M" +
            "UN.INCID_INFO.SERV. do ANEXO I Regra de formação - 6 dígitos numéricos sendo: 2 " +
            "para Item (LC 116/2003), 2 para Subitem (LC 116/2003) e 2 para Desdobro Nacional"))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{6}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cTribNac")]
        public string CTribNac { get; set; }
        
        /// <summary>
        /// <para>Código de tributação municipal do ISSQN</para>
        /// <para>Código de tributação municipal do ISSQN</para>
        /// <para xml:lang="en">Pattern: [0-9]{10}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código de tributação municipal do ISSQN")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{10}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cTribMun")]
        public string CTribMun { get; set; }
        
        /// <summary>
        /// <para>Descrição completa do serviço prestado</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 2000.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Descrição completa do serviço prestado")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2000)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xDescServ")]
        public string XDescServ { get; set; }
        
        /// <summary>
        /// <para>Código NBS correspondente ao serviço prestado, seguindo a versão 2.0, conforme Anexo B</para>
        /// <para>Código da lista de Nomenclatura Brasileira de Serviços (NBS)</para>
        /// <para xml:lang="en">Pattern: [0-9]{9}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Código NBS correspondente ao serviço prestado, seguindo a versão 2.0, conforme An" +
            "exo B"))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{9}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cNBS")]
        public string Cnbs { get; set; }
        
        /// <summary>
        /// <para>Código interno do contribuinte</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// <para xml:lang="en">Pattern: [a-zA-Z0-9]{1,20}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código interno do contribuinte")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(20)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[a-zA-Z0-9]{1,20}")]
        [System.Xml.Serialization.XmlElementAttribute("cIntContrib")]
        public string CIntContrib { get; set; }
    }
}
