//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCEmitente", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcEmitente
    {
        
        /// <summary>
        /// <para>Número do CNPJ do emitente da NFS-e.</para>
        /// <para>Tipo Número do CNPJ</para>
        /// <para xml:lang="en">Minimum length: 14.</para>
        /// <para xml:lang="en">Maximum length: 14.</para>
        /// <para xml:lang="en">Pattern: [0-9]{14}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número do CNPJ do emitente da NFS-e.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(14)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(14)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{14}")]
        [System.Xml.Serialization.XmlElementAttribute("CNPJ")]
        public string Cnpj { get; set; }
        
        /// <summary>
        /// <para>Número do CPF do emitente da NFS-e.</para>
        /// <para>Tipo Número do CPF</para>
        /// <para xml:lang="en">Maximum length: 11.</para>
        /// <para xml:lang="en">Pattern: [0-9]{11}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número do CPF do emitente da NFS-e.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{11}")]
        [System.Xml.Serialization.XmlElementAttribute("CPF")]
        public string Cpf { get; set; }
        
        /// <summary>
        /// <para>Número da inscrição municipal</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número da inscrição municipal")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("IM")]
        public string Im { get; set; }
        
        /// <summary>
        /// <para>Nome / Razão Social do emitente.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 300.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nome / Razão Social do emitente.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(300)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xNome")]
        public string XNome { get; set; }
        
        /// <summary>
        /// <para>Nome / Fantasia do emitente.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 150.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nome / Fantasia do emitente.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(150)]
        [System.Xml.Serialization.XmlElementAttribute("xFant")]
        public string XFant { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações do endereço nacional do Emitente da NFS-e</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações do endereço nacional do Emitente da NFS-e")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("enderNac")]
        public TcEnderecoEmitente EnderNac { get; set; }
        
        /// <summary>
        /// <para>Número do telefone do emitente.
        ///            (Preencher com o Código DDD + número do telefone.
        ///            Nas operações com exterior é permitido informar o código do país + código da localidade + número do telefone)</para>
        /// <para>Número do telefone do prestador:
        ///        Preencher com o Código DDD + número do telefone.
        ///        Nas operações com exterior é permitido informar o código do país + código da localidade + número do telefone</para>
        /// <para xml:lang="en">Pattern: [0-9]{6,20}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Número do telefone do emitente. (Preencher com o Código DDD + número do telefone." +
            " Nas operações com exterior é permitido informar o código do país + código da lo" +
            "calidade + número do telefone)"))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{6,20}")]
        [System.Xml.Serialization.XmlElementAttribute("fone")]
        public string Fone { get; set; }
        
        /// <summary>
        /// <para>E-mail do emitente.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 80.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("E-mail do emitente.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(80)]
        [System.Xml.Serialization.XmlElementAttribute("email")]
        public string Email { get; set; }
    }
}
