//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCInfEvento", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcInfEvento
    {
        
        /// <summary>
        /// <para>Versão do aplicativo que gerou o pedido do evento.</para>
        /// <para>Tipo Versão do Aplicativo que gerou o documento fiscal</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Versão do aplicativo que gerou o pedido do evento.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(20)]
        [System.Xml.Serialization.XmlElementAttribute("verAplic")]
        public string VerAplic { get; set; }
        
        /// <summary>
        /// <para>Ambiente gerador do evento</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Ambiente gerador do evento")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ambGer")]
        public TsAmbGeradorEvt AmbGer { get; set; }
        
        /// <summary>
        /// <para>Sequencial do evento para o mesmo tipo de evento. Para maioria dos eventos nSeqEvento=1. Nos casos em que possa existir mais de um evento do mesmo tipo o ambiente gerador deverá numerar de forma sequencial.</para>
        /// <para>Número com 3 dígitos</para>
        /// <para xml:lang="en">Maximum length: 3.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1}[0-9]{0,2}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Sequencial do evento para o mesmo tipo de evento. Para maioria dos eventos nSeqEv" +
            "ento=1. Nos casos em que possa existir mais de um evento do mesmo tipo o ambient" +
            "e gerador deverá numerar de forma sequencial."))]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(3)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1}[0-9]{0,2}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("nSeqEvento")]
        public string NSeqEvento { get; set; }
        
        /// <summary>
        /// <para>Data/Hora do registro do evento.
        ///            Data e hora no formato UTC (Universal Coordinated Time): AAAA-MM-DDThh:mm:ssTZD"</para>
        /// <para>Data e Hora, formato UTC (AAAA-MM-DDThh:mm:ssTZD, onde TZD = +hh:mm ou -hh:mm)</para>
        /// <para xml:lang="en">Pattern: (((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30)))))T(20|21|22|23|[0-1]\d):[0-5]\d:[0-5]\d([\-,\+](0[0-9]|10|11):00|([\+](12):00)).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Data/Hora do registro do evento. Data e hora no formato UTC (Universal Coordinate" +
            "d Time): AAAA-MM-DDThh:mm:ssTZD\""))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute(("(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-" +
            "((0[1-9])|(1\\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29" +
            "|30)))))T(20|21|22|23|[0-1]\\d):[0-5]\\d:[0-5]\\d([\\-,\\+](0[0-9]|10|11):00|([\\+](12" +
            "):00))"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dhProc")]
        public string DhProc { get; set; }
        
        /// <summary>
        /// <para>Número sequencial do documento gerado por ambiente gerador de DFe do município.</para>
        /// <para>Número sequencial do documento gerado por ambiente gerador de DFe do município.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,13}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número sequencial do documento gerado por ambiente gerador de DFe do município.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,13}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("nDFe")]
        public string NdFe { get; set; }
        
        /// <summary>
        /// <para>Leiaute do pedido de registro do evento gerado pelo autor do evento</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Leiaute do pedido de registro do evento gerado pelo autor do evento")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("pedRegEvento")]
        public TcPedRegEvt PedRegEvento { get; set; }
        
        /// <summary>
        /// <para>Identificador do evento: "EVT" + Chave de acesso(50) Tipo do evento (6) + Pedido de Registro do Evento(3) (nPedRegEvento)</para>
        /// <para xml:lang="en">Maximum length: 62.</para>
        /// <para xml:lang="en">Pattern: EVT[0-9]{59}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(62)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("EVT[0-9]{59}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Id")]
        public string Id { get; set; }
    }
}
