//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCIssqn", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcIssqn
    {
        
        /// <summary>
        /// <para>Valor monetário (R$) de dedução/redução da base de cálculo (BC) do ISSQN.</para>
        /// <para>Valor decimal com 1 a 15 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor monetário (R$) de dedução/redução da base de cálculo (BC) do ISSQN.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vCalcDR")]
        public string VCalcDr { get; set; }
        
        /// <summary>
        /// <para>Tipo Benefício Municipal (BM):
        ///            1) Isenção;
        ///            2) Redução da BC em 'ppBM' %;
        ///            3) Redução da BC em R$ 'vInfoBM';
        ///            4) Alíquota Diferenciada de 'aliqDifBM' %;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Tipo Benefício Municipal (BM): 1) Isenção; 2) Redução da BC em \'ppBM\' %; 3) Reduç" +
            "ão da BC em R$ \'vInfoBM\'; 4) Alíquota Diferenciada de \'aliqDifBM\' %;"))]
        [System.Xml.Serialization.XmlElementAttribute("tpBM")]
        public Tbmissqn TpBm { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TpBm property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TpBmSpecified { get; set; }
        
        /// <summary>
        /// <para>Valor monetário (R$) do percentual de redução da base de cálculo (BC) do ISSQN devido a um benefício municipal (BM).</para>
        /// <para>Valor decimal com 1 a 15 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Valor monetário (R$) do percentual de redução da base de cálculo (BC) do ISSQN de" +
            "vido a um benefício municipal (BM)."))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vCalcBM")]
        public string VCalcBm { get; set; }
        
        /// <summary>
        /// <para>Valor da Base de Cálculo do ISSQN (R$) = Valor do Serviço - Desconto Incondicionado - Deduções/Reduções - Benefício Municipal
        ///            vBC = vServ - descIncond - (vDR ou vCalcDR + vCalcReeRepRes) - (vRedBCBM ou VCalcBM)</para>
        /// <para>Valor decimal com 1 a 15 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Valor da Base de Cálculo do ISSQN (R$) = Valor do Serviço - Desconto Incondiciona" +
            "do - Deduções/Reduções - Benefício Municipal vBC = vServ - descIncond - (vDR ou " +
            "vCalcDR + vCalcReeRepRes) - (vRedBCBM ou VCalcBM)"))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vBC")]
        public string Vbc { get; set; }
        
        /// <summary>
        /// <para>Alíquota aplicada sobre a base de cálculo para apuração do ISSQN.</para>
        /// <para>Valor decimal com 1 dígito mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|[0-9]{1}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Alíquota aplicada sobre a base de cálculo para apuração do ISSQN.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|[0-9]{1}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("pAliqAplic")]
        public string PAliqAplic { get; set; }
        
        /// <summary>
        /// <para>Valor do ISSQN (R$) = Valor da Base de Cálculo x Alíquota ISSQN = vBC x pAliqAplic</para>
        /// <para>Valor decimal com 1 a 15 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Valor do ISSQN (R$) = Valor da Base de Cálculo x Alíquota ISSQN = vBC x pAliqApli" +
            "c"))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vISSQN")]
        public string Vissqn { get; set; }
        
        /// <summary>
        /// <para>Valor total de retenções = Σ(CP + IRRF + CSLL  + ISSQN* +  (PIS + COFINS)**)
        ///            vTotalRet (R$) = (vRetCP + vRetIRRF + vRetCSLL) + vISSQN* + (vPIS + vCOFINS)**</para>
        /// <para>Valor decimal com 1 a 15 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Valor total de retenções = Σ(CP + IRRF + CSLL + ISSQN* + (PIS + COFINS)**) vTotal" +
            "Ret (R$) = (vRetCP + vRetIRRF + vRetCSLL) + vISSQN* + (vPIS + vCOFINS)**"))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vTotalRet")]
        public string VTotalRet { get; set; }
        
        /// <summary>
        /// <para>Valor líquido = Valor do serviço - Desconto condicionado - Desconto incondicionado - Valores retidos (CP, IRRF, CSLL)* - Valores, se retidos (ISSQN, PIS, COFINS)**
        ///            Valor Líquido (R$) = vServ – vDescIncond – vDescCond – (vRetCP + vRetIRRF + vRetCSLL)* – (vISSQN - vPIS + vCOFINS)**</para>
        /// <para>Valor decimal com 1 a 15 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Valor líquido = Valor do serviço - Desconto condicionado - Desconto incondicionado - Valores retidos (CP, IRRF, CSLL)* - Valores, se retidos (ISSQN, PIS, COFINS)** Valor Líquido (R$) = vServ – vDescIncond – vDescCond – (vRetCP + vRetIRRF + vRetCSLL)* – (vISSQN - vPIS + vCOFINS)**")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\\.[0-9]{2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("vLiq")]
        public string VLiq { get; set; }
        
        /// <summary>
        /// <para>Uso da Administração Tributária Municipal.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 2000.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Uso da Administração Tributária Municipal.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2000)]
        [System.Xml.Serialization.XmlElementAttribute("xOutInf")]
        public string XOutInf { get; set; }
    }
}
