//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tcLinks", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Links", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public partial class TcLinks
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("IdentificacaoNfse")]
        public TcIdentificacaoNfse IdentificacaoNfse { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("IdentificacaoDps")]
        public TcIdentificacaoDps IdentificacaoDps { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 2000.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2000)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("UrlVisualizacaoNfse")]
        public string UrlVisualizacaoNfse { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 2000.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(2000)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("UrlVerificaAutenticidade")]
        public string UrlVerificaAutenticidade { get; set; }
    }
}
