//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCLocPrest", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcLocPrest
    {
        
        /// <summary>
        /// <para>Código do município onde o serviço foi prestado (tabela do IBGE)</para>
        /// <para>Tipo Código do Município segundo tabela IBGE</para>
        /// <para xml:lang="en">Pattern: [0-9]{7}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código do município onde o serviço foi prestado (tabela do IBGE)")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{7}")]
        [System.Xml.Serialization.XmlElementAttribute("cLocPrestacao")]
        public string CLocPrestacao { get; set; }
        
        /// <summary>
        /// <para>Código do país onde o serviço foi prestado (Tabela de Países ISO)</para>
        /// <para>Tipo Código do País segundo tabela ISO</para>
        /// <para xml:lang="en">Pattern: [A-Z]{2}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código do país onde o serviço foi prestado (Tabela de Países ISO)")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Z]{2}")]
        [System.Xml.Serialization.XmlElementAttribute("cPaisPrestacao")]
        public string CPaisPrestacao { get; set; }
    }
}
