//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tcPessoasAutorizada", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcPessoasAutorizada
    {
        
        /// <summary>
        /// <para>Tipo Número do CNPJ</para>
        /// <para xml:lang="en">Minimum length: 14.</para>
        /// <para xml:lang="en">Maximum length: 14.</para>
        /// <para xml:lang="en">Pattern: [0-9]{14}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(14)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(14)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{14}")]
        [System.Xml.Serialization.XmlElementAttribute("CNPJ")]
        public string Cnpj { get; set; }
        
        /// <summary>
        /// <para>Tipo Número do CPF</para>
        /// <para xml:lang="en">Maximum length: 11.</para>
        /// <para xml:lang="en">Pattern: [0-9]{11}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{11}")]
        [System.Xml.Serialization.XmlElementAttribute("CPF")]
        public string Cpf { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 300.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(300)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("RazaoSocial")]
        public string RazaoSocial { get; set; }
    }
}
