//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCRegTrib", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcRegTrib
    {
        
        /// <summary>
        /// <para>Situação perante o Simples Nacional:
        ///            1 - Não Optante;
        ///            2 - Optante - Microempreendedor Individual (MEI);
        ///            3 - Optante - Microempresa ou Empresa de Pequeno Porte (ME/EPP);</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Situação perante o Simples Nacional: 1 - Não Optante; 2 - Optante - Microempreend" +
            "edor Individual (MEI); 3 - Optante - Microempresa ou Empresa de Pequeno Porte (M" +
            "E/EPP);"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("opSimpNac")]
        public TsOpSimpNac OpSimpNac { get; set; }
        
        /// <summary>
        /// <para>Opção para que o contribuinte optante pelo Simples Nacional ME/EPP (opSimpNac = 3) possa indicar, ao emitir o documento fiscal, em qual regime de apuração os tributos federais e municipal estão inseridos, caso tenha ultrapassado algum sublimite ou limite definido para o Simples Nacional.
        ///            1 – Regime de apuração dos tributos federais e municipal pelo SN;
        ///            2 – Regime de apuração dos tributos federais pelo SN e ISSQN  por fora do SN conforme respectiva legislação municipal do tributo;
        ///            3 – Regime de apuração dos tributos federais e municipal por fora do SN conforme respectivas legilações federal e municipal de cada tributo;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Opção para que o contribuinte optante pelo Simples Nacional ME/EPP (opSimpNac = 3) possa indicar, ao emitir o documento fiscal, em qual regime de apuração os tributos federais e municipal estão inseridos, caso tenha ultrapassado algum sublimite ou limite definido para o Simples Nacional. 1 – Regime de apuração dos tributos federais e municipal pelo SN; 2 – Regime de apuração dos tributos federais pelo SN e ISSQN por fora do SN conforme respectiva legislação municipal do tributo; 3 – Regime de apuração dos tributos federais e municipal por fora do SN conforme respectivas legilações federal e municipal de cada tributo;")]
        [System.Xml.Serialization.XmlElementAttribute("regApTribSN")]
        public TsRegimeApuracaoSimpNac RegApTribSn { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the RegApTribSn property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegApTribSnSpecified { get; set; }
        
        /// <summary>
        /// <para>Tipos de Regimes Especiais de Tributação:
        ///            0 - Nenhum;
        ///            1 - Ato Cooperado (Cooperativa);
        ///            2 - Estimativa;
        ///            3 - Microempresa Municipal;
        ///            4 - Notário ou Registrador;
        ///            5 - Profissional Autônomo;
        ///            6 - Sociedade de Profissionais;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Tipos de Regimes Especiais de Tributação: 0 - Nenhum; 1 - Ato Cooperado (Cooperat" +
            "iva); 2 - Estimativa; 3 - Microempresa Municipal; 4 - Notário ou Registrador; 5 " +
            "- Profissional Autônomo; 6 - Sociedade de Profissionais;"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("regEspTrib")]
        public TsRegEspTrib RegEspTrib { get; set; }
    }
}
