//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCRTCInfoImovel", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcrtcInfoImovel
    {
        
        /// <summary>
        /// <para>Inscrição imobiliária fiscal (código fornecido pela Prefeitura Municipal para a identificação da obra ou para fins de recolhimento do IPTU)</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 30.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Inscrição imobiliária fiscal (código fornecido pela Prefeitura Municipal para a i" +
            "dentificação da obra ou para fins de recolhimento do IPTU)"))]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(30)]
        [System.Xml.Serialization.XmlElementAttribute("inscImobFisc")]
        public string InscImobFisc { get; set; }
        
        /// <summary>
        /// <para>Código do Cadastro Imobiliário Brasileiro - CIB</para>
        /// <para xml:lang="en">Minimum length: 8.</para>
        /// <para xml:lang="en">Maximum length: 8.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código do Cadastro Imobiliário Brasileiro - CIB")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(8)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(8)]
        [System.Xml.Serialization.XmlElementAttribute("cCIB")]
        public string Ccib { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações do endereço da obra do serviço prestado</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações do endereço da obra do serviço prestado")]
        [System.Xml.Serialization.XmlElementAttribute("end")]
        public TcEnderObraEvento End { get; set; }
    }
}
