//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCRTCIBSCBS", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Tcrtcibscbs
    {
        
        /// <summary>
        /// <para>Código IBGE da localidade de incidência do IBS/CBS (local da operação)</para>
        /// <para>Tipo Código do Município segundo tabela IBGE</para>
        /// <para xml:lang="en">Pattern: [0-9]{7}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código IBGE da localidade de incidência do IBS/CBS (local da operação)")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{7}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cLocalidadeIncid")]
        public string CLocalidadeIncid { get; set; }
        
        /// <summary>
        /// <para>Nome da localidade de incidência do IBS/CBS</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 600.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nome da localidade de incidência do IBS/CBS")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(600)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xLocalidadeIncid")]
        public string XLocalidadeIncid { get; set; }
        
        /// <summary>
        /// <para>Percentual de redução de aliquota em compra governamental</para>
        /// <para>Valor decimal com 1 ou 2 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,1}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Percentual de redução de aliquota em compra governamental")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,1}(\\.[0-9]{2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("pRedutor")]
        public string PRedutor { get; set; }
        
        /// <summary>
        /// <para>Grupo de valores brutos referentes ao IBS/CBS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de valores brutos referentes ao IBS/CBS")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("valores")]
        public TcrtcValoresIbscbs Valores { get; set; }
        
        /// <summary>
        /// <para>Grupo de Totalizadores</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de Totalizadores")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("totCIBS")]
        public TcrtcTotalCibs TotCibs { get; set; }
    }
}
