//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCRTCListaDoc", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcrtcListaDoc
    {
        
        /// <summary>
        /// <para>Grupo de informações de documentos fiscais eletrônicos que se encontram no repositório nacional</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Grupo de informações de documentos fiscais eletrônicos que se encontram no reposi" +
            "tório nacional"))]
        [System.Xml.Serialization.XmlElementAttribute("dFeNacional")]
        public TcrtcListaDocDFe DFeNacional { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações de documento fiscais, eletrônicos ou não, que não se encontram no repositório nacional</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Grupo de informações de documento fiscais, eletrônicos ou não, que não se encontr" +
            "am no repositório nacional"))]
        [System.Xml.Serialization.XmlElementAttribute("docFiscalOutro")]
        public TcrtcListaDocFiscalOutro DocFiscalOutro { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações de documento não fiscal.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações de documento não fiscal.")]
        [System.Xml.Serialization.XmlElementAttribute("docOutro")]
        public TcrtcListaDocOutro DocOutro { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações do fornecedor do documento referenciado</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações do fornecedor do documento referenciado")]
        [System.Xml.Serialization.XmlElementAttribute("fornec")]
        public TcrtcListaDocFornec Fornec { get; set; }
        
        /// <summary>
        /// <para>Data da emissão do documento dedutível. Ano, mês e dia (AAAA-MM-DD).</para>
        /// <para>Tipo data no formato AAAA-MM-DD</para>
        /// <para xml:lang="en">Pattern: (((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30))))).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data da emissão do documento dedutível. Ano, mês e dia (AAAA-MM-DD).")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute(("(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-" +
            "((0[1-9])|(1\\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29" +
            "|30)))))"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dtEmiDoc")]
        public string DtEmiDoc { get; set; }
        
        /// <summary>
        /// <para>Data da competência do documento dedutível. Ano, mês e dia (AAAA-MM-DD)</para>
        /// <para>Tipo data no formato AAAA-MM-DD</para>
        /// <para xml:lang="en">Pattern: (((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30))))).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data da competência do documento dedutível. Ano, mês e dia (AAAA-MM-DD)")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute(("(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-" +
            "((0[1-9])|(1\\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29" +
            "|30)))))"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dtCompDoc")]
        public string DtCompDoc { get; set; }
        
        /// <summary>
        /// <para>Tipo de valor incluído neste documento, recebido por motivo de estarem relacionadas a operações de terceiros, 
        ///            objeto de reembolso, repasse ou ressarcimento pelo recebedor, já tributados e aqui referenciados</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Tipo de valor incluído neste documento, recebido por motivo de estarem relacionad" +
            "as a operações de terceiros, objeto de reembolso, repasse ou ressarcimento pelo " +
            "recebedor, já tributados e aqui referenciados"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("tpReeRepRes")]
        public TsrtcTpReeRepRes TpReeRepRes { get; set; }
        
        /// <summary>
        /// <para>Descrição do reembolso ou ressarcimento quando a opção é 
        ///            "99 – Outros reembolsos ou ressarcimentos recebidos por valores pagos relativos a operações por conta e ordem de terceiro"</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 150.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Descrição do reembolso ou ressarcimento quando a opção é \"99 – Outros reembolsos " +
            "ou ressarcimentos recebidos por valores pagos relativos a operações por conta e " +
            "ordem de terceiro\""))]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(150)]
        [System.Xml.Serialization.XmlElementAttribute("xTpReeRepRes")]
        public string XTpReeRepRes { get; set; }
        
        /// <summary>
        /// <para>Valor monetário (total ou parcial, conforme documento informado) utilizado para não inclusão na base de cálculo 
        ///            do ISS e do IBS e da CBS da NFS-e que está sendo emitida (R$)</para>
        /// <para>Valor decimal com 1 a 15 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Valor monetário (total ou parcial, conforme documento informado) utilizado para n" +
            "ão inclusão na base de cálculo do ISS e do IBS e da CBS da NFS-e que está sendo " +
            "emitida (R$)"))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\\.[0-9]{2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("vlrReeRepRes")]
        public string VlrReeRepRes { get; set; }
    }
}
