//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCRTCListaDocDFe", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcrtcListaDocDFe
    {
        
        /// <summary>
        /// <para>Documento fiscal a que se refere a chaveDfe que seja um dos documentos do Repositório Nacional</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Documento fiscal a que se refere a chaveDfe que seja um dos documentos do Reposit" +
            "ório Nacional"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("tipoChaveDFe")]
        public TsrtcTipoChaveDFe TipoChaveDFe { get; set; }
        
        /// <summary>
        /// <para>Descrição da DF-e a que se refere a chaveDfe que seja um dos documentos do Repositório Nacional
        ///            Deve ser preenchido apenas quando "tipoChaveDFe = 9 (Outro)"</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Descrição da DF-e a que se refere a chaveDfe que seja um dos documentos do Reposi" +
            "tório Nacional Deve ser preenchido apenas quando \"tipoChaveDFe = 9 (Outro)\""))]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("xTipoChaveDFe")]
        public string XTipoChaveDFe { get; set; }
        
        /// <summary>
        /// <para>Chave do Documento Fiscal eletrônico do repositório nacional referenciado para os casos de operações já tributadas</para>
        /// <para>Chave do Documento Fiscal Eletrônico</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Chave do Documento Fiscal eletrônico do repositório nacional referenciado para os" +
            " casos de operações já tributadas"))]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("chaveDFe")]
        public string ChaveDFe { get; set; }
    }
}
