//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCRTCTotalIBS", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcrtcTotalIbs
    {
        
        /// <summary>
        /// <para>Valor total do IBS. (vIBSTot = vIBSUF + vIBSMun)</para>
        /// <para>Valor decimal com 1 a 15 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor total do IBS. (vIBSTot = vIBSUF + vIBSMun)")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\\.[0-9]{2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("vIBSTot")]
        public string VibsTot { get; set; }
        
        /// <summary>
        /// <para>Grupo de valores referentes ao crédito presumido para IBS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de valores referentes ao crédito presumido para IBS")]
        [System.Xml.Serialization.XmlElementAttribute("gIBSCredPres")]
        public TcrtcTotalIbsCredPres GibsCredPres { get; set; }
        
        /// <summary>
        /// <para>Grupo de valores referentes ao IBS Estadual</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de valores referentes ao IBS Estadual")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("gIBSUFTot")]
        public TcrtcTotalIbsuf GibsufTot { get; set; }
        
        /// <summary>
        /// <para>Grupo de valores referentes ao IBS Municipal</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de valores referentes ao IBS Municipal")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("gIBSMunTot")]
        public TcrtcTotalIbsMun GibsMunTot { get; set; }
    }
}
