//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCRTCInfoTributosSitClas", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcrtcInfoTributosSitClas
    {
        
        /// <summary>
        /// <para>Código de Situação Tributária do IBS e da CBS</para>
        /// <para>Código de Situação Tributária</para>
        /// <para xml:lang="en">Pattern: [0-9]{3}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código de Situação Tributária do IBS e da CBS")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{3}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CST")]
        public string Cst { get; set; }
        
        /// <summary>
        /// <para>Código de Classificação Tributária do IBS e da CBS</para>
        /// <para>Código de Classificação Tributária</para>
        /// <para xml:lang="en">Pattern: [0-9]{6}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código de Classificação Tributária do IBS e da CBS")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{6}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cClassTrib")]
        public string CClassTrib { get; set; }
        
        /// <summary>
        /// <para>Código e Classificação do Crédito Presumido: IBS e CBS</para>
        /// <para>Código e Classificação do Crédito Presumido</para>
        /// <para xml:lang="en">Pattern: [0-9]{2}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Código e Classificação do Crédito Presumido: IBS e CBS")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{2}")]
        [System.Xml.Serialization.XmlElementAttribute("cCredPres")]
        public string CCredPres { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações da Tributação Regular</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações da Tributação Regular")]
        [System.Xml.Serialization.XmlElementAttribute("gTribRegular")]
        public TcrtcInfoTributosTribRegular GTribRegular { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações relacionadas ao diferimento para IBS e CBS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações relacionadas ao diferimento para IBS e CBS")]
        [System.Xml.Serialization.XmlElementAttribute("gDif")]
        public TcrtcInfoTributosDif GDif { get; set; }
    }
}
