//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCSubstituicao", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcSubstituicao
    {
        
        /// <summary>
        /// <para>Chave de acesso da NFS-e a ser substituída</para>
        /// <para>Tipo Chave da Nota Fiscal de Serviço Eletrônica</para>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// <para xml:lang="en">Pattern: [0-9]{50}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Chave de acesso da NFS-e a ser substituída")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{50}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("chSubstda")]
        public string ChSubstda { get; set; }
        
        /// <summary>
        /// <para>Código de justificativa para substituição de NFS-e:
        ///            01 - Desenquadramento de NFS-e do Simples Nacional;
        ///            02 - Enquadramento de NFS-e no Simples Nacional;
        ///            03 - Inclusão Retroativa de Imunidade/Isenção para NFS-e;
        ///            04 - Exclusão Retroativa de Imunidade/Isenção para NFS-e;
        ///            05 - Rejeição de NFS-e pelo tomador ou pelo intermediário se responsável pelo recolhimento do tributo;
        ///            99 - Outros;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Código de justificativa para substituição de NFS-e: 01 - Desenquadramento de NFS-e do Simples Nacional; 02 - Enquadramento de NFS-e no Simples Nacional; 03 - Inclusão Retroativa de Imunidade/Isenção para NFS-e; 04 - Exclusão Retroativa de Imunidade/Isenção para NFS-e; 05 - Rejeição de NFS-e pelo tomador ou pelo intermediário se responsável pelo recolhimento do tributo; 99 - Outros;")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cMotivo")]
        public TsCodJustSubst CMotivo { get; set; }
        
        /// <summary>
        /// <para>Descrição do motivo da substituição da NFS-e
        ///            O emitente deve descrever o motivo da substituição para outros motivos (cMotivo = 99).</para>
        /// <para>Descrição do motivo da substituição da NFS-e</para>
        /// <para xml:lang="en">Minimum length: 15.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Descrição do motivo da substituição da NFS-e O emitente deve descrever o motivo d" +
            "a substituição para outros motivos (cMotivo = 99)."))]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.Xml.Serialization.XmlElementAttribute("xMotivo")]
        public string XMotivo { get; set; }
    }
}
