//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCTribMunicipal", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcTribMunicipal
    {
        
        /// <summary>
        /// <para>Tributação do ISSQN sobre o serviço prestado:
        ///            1 - Operação tributável;
        ///            2 - Imunidade;
        ///            3 - Exportação de serviço;
        ///            4 - Não Incidência;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Tributação do ISSQN sobre o serviço prestado: 1 - Operação tributável; 2 - Imunid" +
            "ade; 3 - Exportação de serviço; 4 - Não Incidência;"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("tribISSQN")]
        public TsTribIssqn TribIssqn { get; set; }
        
        /// <summary>
        /// <para>Código do país onde se verficou o resultado da prestação do serviço para o caso de Exportação de Serviço.(Tabela de Países ISO)</para>
        /// <para>Tipo Código do País segundo tabela ISO</para>
        /// <para xml:lang="en">Pattern: [A-Z]{2}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Código do país onde se verficou o resultado da prestação do serviço para o caso d" +
            "e Exportação de Serviço.(Tabela de Países ISO)"))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[A-Z]{2}")]
        [System.Xml.Serialization.XmlElementAttribute("cPaisResult")]
        public string CPaisResult { get; set; }
        
        /// <summary>
        /// <para>Identificação da Imunidade do ISSQN – somente para o caso de Imunidade.
        ///            Tipos de Imunidades:            
        ///            0 - Imunidade (tipo não informado na nota de origem);
        ///            1 - Patrimônio, renda ou serviços, uns dos outros (CF88, Art 150, VI, a);
        ///            2 - Templos de qualquer culto (CF88, Art 150, VI, b);
        ///            3 - Patrimônio, renda ou serviços dos partidos políticos, inclusive suas fundações, das entidades sindicais dos trabalhadores, das instituições de educação e de assistência social, sem fins lucrativos, atendidos os requisitos da lei (CF88, Art 150, VI, c);
        ///            4 - Livros, jornais, periódicos e o papel destinado a sua impressão (CF88, Art 150, VI, d);
        ///            5 - Fonogramas e videofonogramas musicais produzidos no Brasil contendo obras musicais ou literomusicais de autores brasileiros e/ou obras em geral interpretadas por artistas brasileiros bem como os suportes materiais ou arquivos digitais que os contenham, salvo na etapa de replicação industrial de mídias ópticas de leitura a laser.   (CF88, Art 150, VI, e);</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Identificação da Imunidade do ISSQN – somente para o caso de Imunidade. Tipos de Imunidades: 0 - Imunidade (tipo não informado na nota de origem); 1 - Patrimônio, renda ou serviços, uns dos outros (CF88, Art 150, VI, a); 2 - Templos de qualquer culto (CF88, Art 150, VI, b); 3 - Patrimônio, renda ou serviços dos partidos políticos, inclusive suas fundações, das entidades sindicais dos trabalhadores, das instituições de educação e de assistência social, sem fins lucrativos, atendidos os requisitos da lei (CF88, Art 150, VI, c); 4 - Livros, jornais, periódicos e o papel destinado a sua impressão (CF88, Art 150, VI, d); 5 - Fonogramas e videofonogramas musicais produzidos no Brasil contendo obras musicais ou literomusicais de autores brasileiros e/ou obras em geral interpretadas por artistas brasileiros bem como os suportes materiais ou arquivos digitais que os contenham, salvo na etapa de replicação industrial de mídias ópticas de leitura a laser. (CF88, Art 150, VI, e);")]
        [System.Xml.Serialization.XmlElementAttribute("tpImunidade")]
        public TsTipoImunidadeIssqn TpImunidade { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TpImunidade property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TpImunidadeSpecified { get; set; }
        
        /// <summary>
        /// <para>Informações para a suspensão da Exigibilidade do ISSQN</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informações para a suspensão da Exigibilidade do ISSQN")]
        [System.Xml.Serialization.XmlElementAttribute("exigSusp")]
        public TcExigSuspensa ExigSusp { get; set; }
        
        /// <summary>
        /// <para>Tributação do ISSQN sobre o serviço prestado:
        ///            1 - Operação tributável;
        ///            2 - Exportação de serviço;
        ///            3 - Não Incidência;
        ///            4 - Imunidade;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Tributação do ISSQN sobre o serviço prestado: 1 - Operação tributável; 2 - Export" +
            "ação de serviço; 3 - Não Incidência; 4 - Imunidade;"))]
        [System.Xml.Serialization.XmlElementAttribute("BM")]
        public TcBeneficioMunicipal Bm { get; set; }
        
        /// <summary>
        /// <para>Tipo de retencao do ISSQN:
        ///            1 - Não Retido;
        ///            2 - Retido pelo Tomador;
        ///            3 - Retido pelo Intermediario;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Tipo de retencao do ISSQN: 1 - Não Retido; 2 - Retido pelo Tomador; 3 - Retido pe" +
            "lo Intermediario;"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("tpRetISSQN")]
        public TsTipoRetIssqn TpRetIssqn { get; set; }
        
        /// <summary>
        /// <para>Valor da alíquota (%) do serviço prestado relativo ao município sujeito ativo (município de incidência) do ISSQN.
        ///            Se o município de incidência pertence ao Sistema Nacional NFS-e a alíquota estará parametrizada e, portanto, será fornecida pelo sistema.
        ///            Se o município de incidência não pertence ao Sistema Nacional NFS-e a alíquota não estará parametrizada e, por isso, deverá ser fornecida pelo emitente.</para>
        /// <para>Valor decimal com 1 dígito mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|[0-9]{1}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Valor da alíquota (%) do serviço prestado relativo ao município sujeito ativo (município de incidência) do ISSQN. Se o município de incidência pertence ao Sistema Nacional NFS-e a alíquota estará parametrizada e, portanto, será fornecida pelo sistema. Se o município de incidência não pertence ao Sistema Nacional NFS-e a alíquota não estará parametrizada e, por isso, deverá ser fornecida pelo emitente.")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|[0-9]{1}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("pAliq")]
        public string PAliq { get; set; }
    }
}
