//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCTribOutrosPisCofins", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcTribOutrosPisCofins
    {
        
        /// <summary>
        /// <para>Código de Situação Tributária do PIS/COFINS (CST):
        ///            00 - Nenhum;      
        ///            01 - Operação Tributável com Alíquota Básica;
        ///            02 - Operação Tributável com Alíquota Diferenciada;
        ///            03 - Operação Tributável com Alíquota por Unidade de Medida de Produto;
        ///            04 - Operação Tributável monofásica - Revenda a Alíquota Zero;
        ///            05 - Operação Tributável por Substituição Tributária;
        ///            06 - Operação Tributável a Alíquota Zero;
        ///            07 - Operação Tributável da Contribuição;
        ///            08 - Operação sem Incidência da Contribuição;
        ///            09 - Operação com Suspensão da Contribuição;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"Código de Situação Tributária do PIS/COFINS (CST): 00 - Nenhum; 01 - Operação Tributável com Alíquota Básica; 02 - Operação Tributável com Alíquota Diferenciada; 03 - Operação Tributável com Alíquota por Unidade de Medida de Produto; 04 - Operação Tributável monofásica - Revenda a Alíquota Zero; 05 - Operação Tributável por Substituição Tributária; 06 - Operação Tributável a Alíquota Zero; 07 - Operação Tributável da Contribuição; 08 - Operação sem Incidência da Contribuição; 09 - Operação com Suspensão da Contribuição;")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CST")]
        public TsTipoCst Cst { get; set; }
        
        /// <summary>
        /// <para>Valor da Base de Cálculo do PIS/COFINS (R$).</para>
        /// <para>Valor decimal com 1 a 15 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor da Base de Cálculo do PIS/COFINS (R$).")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vBCPisCofins")]
        public string VbcPisCofins { get; set; }
        
        /// <summary>
        /// <para>Valor da Alíquota do PIS (%).</para>
        /// <para>Valor decimal com 1 ou 2 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,1}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor da Alíquota do PIS (%).")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,1}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("pAliqPis")]
        public string PAliqPis { get; set; }
        
        /// <summary>
        /// <para>Valor da Alíquota da COFINS (%).</para>
        /// <para>Valor decimal com 1 ou 2 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,1}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor da Alíquota da COFINS (%).")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,1}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("pAliqCofins")]
        public string PAliqCofins { get; set; }
        
        /// <summary>
        /// <para>Valor monetário do PIS (R$).</para>
        /// <para>Valor decimal com 1 a 15 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor monetário do PIS (R$).")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vPis")]
        public string VPis { get; set; }
        
        /// <summary>
        /// <para>Valor monetário do COFINS (R$).</para>
        /// <para>Valor decimal com 1 a 15 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor monetário do COFINS (R$).")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vCofins")]
        public string VCofins { get; set; }
        
        /// <summary>
        /// <para>Tipo de retencao do Pis/Cofins:
        ///            1 - Retido;
        ///            2 - Não Retido;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tipo de retencao do Pis/Cofins: 1 - Retido; 2 - Não Retido;")]
        [System.Xml.Serialization.XmlElementAttribute("tpRetPisCofins")]
        public TsTipoRetPisCofins TpRetPisCofins { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TpRetPisCofins property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TpRetPisCofinsSpecified { get; set; }
    }
}
