//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    /// <summary>
    /// <para>Código de justificativa para substituição de NFS-e:
    ///        01 - Desenquadramento de NFS-e do Simples Nacional;
    ///        02 - Enquadramento de NFS-e no Simples Nacional;
    ///        03 - Inclusão Retroativa de Imunidade/Isenção para NFS-e;
    ///        04 - Exclusão Retroativa de Imunidade/Isenção para NFS-e;
    ///        05 - Rejeição de NFS-e pelo tomador ou pelo intermediário se responsável pelo recolhimento do tributo;
    ///        99 - Outros;</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"Código de justificativa para substituição de NFS-e: 01 - Desenquadramento de NFS-e do Simples Nacional; 02 - Enquadramento de NFS-e no Simples Nacional; 03 - Inclusão Retroativa de Imunidade/Isenção para NFS-e; 04 - Exclusão Retroativa de Imunidade/Isenção para NFS-e; 05 - Rejeição de NFS-e pelo tomador ou pelo intermediário se responsável pelo recolhimento do tributo; 99 - Outros;")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TSCodJustSubst", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public enum TsCodJustSubst
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
        
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,
        
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,
        
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }
}
