//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    /// <summary>
    /// <para>Identificação da Dedução/Redução:
    ///        1 – Alimentação e bebidas/frigobar;
    ///        2 – Materiais;
    ///        5 – Repasse consorciado;
    ///        6 – Repasse plano de saúde;
    ///        7 – Serviços;
    ///        8 – Subempreitada de mão de obra;
    ///        99 – Outras deduções;</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Identificação da Dedução/Redução: 1 – Alimentação e bebidas/frigobar; 2 – Materia" +
        "is; 5 – Repasse consorciado; 6 – Repasse plano de saúde; 7 – Serviços; 8 – Subem" +
        "preitada de mão de obra; 99 – Outras deduções;"))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TSIdeDedRed", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public enum TsIdeDedRed
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }
}
