//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    /// <summary>
    /// <para>Vínculo da Operação à Movimentação Temporária de Bens:
    ///        0 - Desconhecido (tipo não informado na nota de origem);
    ///        1 - Não;
    ///        2 - Vinculada - Declaração de Importação;
    ///        3 - Vinculada - Declaração de Exportação;</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Vínculo da Operação à Movimentação Temporária de Bens: 0 - Desconhecido (tipo não" +
        " informado na nota de origem); 1 - Não; 2 - Vinculada - Declaração de Importação" +
        "; 3 - Vinculada - Declaração de Exportação;"))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TSMovTempBens", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public enum TsMovTempBens
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
}
