//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    /// <summary>
    /// <para>Indica operação de uso ou consumo pessoal (art. 57):
    ///        0 - Não;
    ///        1 - Sim;</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Indica operação de uso ou consumo pessoal (art. 57): 0 - Não; 1 - Sim;")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TSRTCIndFinal", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public enum TsrtcIndFinal
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
}
