//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    /// <summary>
    /// <para>Código de Situação Tributária do PIS/COFINS (CST):
    ///        00 - Nenhum;      
    ///        01 - Operação Tributável com Alíquota Básica;
    ///        02 - Operação Tributável com Alíquota Diferenciada;
    ///        03 - Operação Tributável com Alíquota por Unidade de Medida de Produto;
    ///        04 - Operação Tributável monofásica - Revenda a Alíquota Zero;
    ///        05 - Operação Tributável por Substituição Tributária;
    ///        06 - Operação Tributável a Alíquota Zero;
    ///        07 - Operação Tributável da Contribuição;
    ///        08 - Operação sem Incidência da Contribuição;
    ///        09 - Operação com Suspensão da Contribuição;</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"Código de Situação Tributária do PIS/COFINS (CST): 00 - Nenhum; 01 - Operação Tributável com Alíquota Básica; 02 - Operação Tributável com Alíquota Diferenciada; 03 - Operação Tributável com Alíquota por Unidade de Medida de Produto; 04 - Operação Tributável monofásica - Revenda a Alíquota Zero; 05 - Operação Tributável por Substituição Tributária; 06 - Operação Tributável a Alíquota Zero; 07 - Operação Tributável da Contribuição; 08 - Operação sem Incidência da Contribuição; 09 - Operação com Suspensão da Contribuição;")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TSTipoCST", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public enum TsTipoCst
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("00")]
        Item00,
        
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
        
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,
        
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,
        
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,
        
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,
        
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,
        
        [System.Xml.Serialization.XmlEnumAttribute("09")]
        Item09,
    }
}
