//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    /// <summary>
    /// <para>Tipo Sigla da UF</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Tipo Sigla da UF")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TSUF", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public enum Tsuf
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("AC")]
        Ac,
        
        [System.Xml.Serialization.XmlEnumAttribute("AL")]
        Al,
        
        [System.Xml.Serialization.XmlEnumAttribute("AM")]
        Am,
        
        [System.Xml.Serialization.XmlEnumAttribute("AP")]
        Ap,
        
        [System.Xml.Serialization.XmlEnumAttribute("BA")]
        Ba,
        
        [System.Xml.Serialization.XmlEnumAttribute("CE")]
        Ce,
        
        [System.Xml.Serialization.XmlEnumAttribute("DF")]
        Df,
        
        [System.Xml.Serialization.XmlEnumAttribute("ES")]
        Es,
        
        [System.Xml.Serialization.XmlEnumAttribute("GO")]
        Go,
        
        [System.Xml.Serialization.XmlEnumAttribute("MA")]
        Ma,
        
        [System.Xml.Serialization.XmlEnumAttribute("MG")]
        Mg,
        
        [System.Xml.Serialization.XmlEnumAttribute("MS")]
        Ms,
        
        [System.Xml.Serialization.XmlEnumAttribute("MT")]
        Mt,
        
        [System.Xml.Serialization.XmlEnumAttribute("PA")]
        Pa,
        
        [System.Xml.Serialization.XmlEnumAttribute("PB")]
        Pb,
        
        [System.Xml.Serialization.XmlEnumAttribute("PE")]
        Pe,
        
        [System.Xml.Serialization.XmlEnumAttribute("PI")]
        Pi,
        
        [System.Xml.Serialization.XmlEnumAttribute("PR")]
        Pr,
        
        [System.Xml.Serialization.XmlEnumAttribute("RJ")]
        Rj,
        
        [System.Xml.Serialization.XmlEnumAttribute("RN")]
        Rn,
        
        [System.Xml.Serialization.XmlEnumAttribute("RO")]
        Ro,
        
        [System.Xml.Serialization.XmlEnumAttribute("RR")]
        Rr,
        
        [System.Xml.Serialization.XmlEnumAttribute("RS")]
        Rs,
        
        [System.Xml.Serialization.XmlEnumAttribute("SC")]
        Sc,
        
        [System.Xml.Serialization.XmlEnumAttribute("SE")]
        Se,
        
        [System.Xml.Serialization.XmlEnumAttribute("SP")]
        Sp,
        
        [System.Xml.Serialization.XmlEnumAttribute("TO")]
        To,
    }
}
