//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace Abrasf.Core.Models
{
    
    
    /// <summary>
    /// <para>Vínculo entre as partes no negócio:
    ///        0 - Sem vínculo com o Tomador/Prestador
    ///        1 - Controlada;
    ///        2 - Controladora;
    ///        3 - Coligada;
    ///        4 - Matriz;
    ///        5 - Filial ou sucursal;
    ///        6 - Outro vínculo;</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Vínculo entre as partes no negócio: 0 - Sem vínculo com o Tomador/Prestador 1 - C" +
        "ontrolada; 2 - Controladora; 3 - Coligada; 4 - Matriz; 5 - Filial ou sucursal; 6" +
        " - Outro vínculo;"))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TSVincPrest", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public enum TsVincPrest
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
}
