//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ConsultarNfseFaixaResposta", Namespace="http://www.sped.fazenda.gov.br/nfse", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ConsultarNfseFaixaResposta", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public partial class ConsultarNfseFaixaResposta
    {
        
        [System.Xml.Serialization.XmlElementAttribute("ListaNfse")]
        public ConsultarNfseFaixaRespostaListaNfse ListaNfse { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TcMensagemRetorno> _listaMensagemRetorno;
        
        [System.Xml.Serialization.XmlArrayAttribute("ListaMensagemRetorno")]
        [System.Xml.Serialization.XmlArrayItemAttribute("MensagemRetorno", Namespace="http://www.sped.fazenda.gov.br/nfse")]
        public System.Collections.ObjectModel.Collection<TcMensagemRetorno> ListaMensagemRetorno
        {
            get
            {
                return _listaMensagemRetorno;
            }
            private set
            {
                _listaMensagemRetorno = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ListaMensagemRetorno collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListaMensagemRetornoSpecified
        {
            get
            {
                return (this.ListaMensagemRetorno.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ConsultarNfseFaixaResposta" /> class.</para>
        /// </summary>
        public ConsultarNfseFaixaResposta()
        {
            this._listaMensagemRetorno = new System.Collections.ObjectModel.Collection<TcMensagemRetorno>();
        }
    }
}
