//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    /// <summary>
    /// <para>Informações das pessoas envolvidas na NFS-e. Pode ser o tomador, o intermediário ou o fornecedor (dedução/redução)</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Informações das pessoas envolvidas na NFS-e. Pode ser o tomador, o intermediário " +
        "ou o fornecedor (dedução/redução)"))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCInfoPessoa", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcInfoPessoa
    {
        
        /// <summary>
        /// <para>Número do CNPJ</para>
        /// <para>Tipo Número do CNPJ</para>
        /// <para xml:lang="en">Minimum length: 14.</para>
        /// <para xml:lang="en">Maximum length: 14.</para>
        /// <para xml:lang="en">Pattern: [0-9]{14}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número do CNPJ")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(14)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(14)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{14}")]
        [System.Xml.Serialization.XmlElementAttribute("CNPJ")]
        public string Cnpj { get; set; }
        
        /// <summary>
        /// <para>Número do CPF</para>
        /// <para>Tipo Número do CPF</para>
        /// <para xml:lang="en">Maximum length: 11.</para>
        /// <para xml:lang="en">Pattern: [0-9]{11}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número do CPF")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{11}")]
        [System.Xml.Serialization.XmlElementAttribute("CPF")]
        public string Cpf { get; set; }
        
        /// <summary>
        /// <para>Número de Identificação Fiscal fornecido por órgão de administração tributária no exterior</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 40.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Número de Identificação Fiscal fornecido por órgão de administração tributária no" +
            " exterior"))]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(40)]
        [System.Xml.Serialization.XmlElementAttribute("NIF")]
        public string Nif { get; set; }
        
        /// <summary>
        /// <para>Motivo para não informação do NIF:
        ///              0 - Não informado na nota de origem;
        ///              1 - Dispensado do NIF;
        ///              2 - Não exigência do NIF;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Motivo para não informação do NIF: 0 - Não informado na nota de origem; 1 - Dispe" +
            "nsado do NIF; 2 - Não exigência do NIF;"))]
        [System.Xml.Serialization.XmlElementAttribute("cNaoNIF")]
        public TsCodNaoNif CNaoNif { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CNaoNif property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CNaoNifSpecified { get; set; }
        
        /// <summary>
        /// <para>Número do Cadastro de Atividade Econômica da Pessoa Física (CAEPF) do tomador, intermediário ou fornecedor do serviço.</para>
        /// <para>Tipo Número do CAEPF</para>
        /// <para xml:lang="en">Maximum length: 14.</para>
        /// <para xml:lang="en">Pattern: [0-9]{14}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Número do Cadastro de Atividade Econômica da Pessoa Física (CAEPF) do tomador, in" +
            "termediário ou fornecedor do serviço."))]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(14)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{14}")]
        [System.Xml.Serialization.XmlElementAttribute("CAEPF")]
        public string Caepf { get; set; }
        
        /// <summary>
        /// <para>Número da inscrição municipal</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número da inscrição municipal")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.Xml.Serialization.XmlElementAttribute("IM")]
        public string Im { get; set; }
        
        /// <summary>
        /// <para>Nome/Nome Empresarial</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 300.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nome/Nome Empresarial")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(300)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xNome")]
        public string XNome { get; set; }
        
        /// <summary>
        /// <para>Dados de endereço</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Dados de endereço")]
        [System.Xml.Serialization.XmlElementAttribute("end")]
        public TcEndereco End { get; set; }
        
        /// <summary>
        /// <para>Número do telefone do prestador:
        ///            Preencher com o Código DDD + número do telefone.
        ///            Nas operações com exterior é permitido informar o código do país + código da localidade + número do telefone)</para>
        /// <para>Número do telefone do prestador:
        ///        Preencher com o Código DDD + número do telefone.
        ///        Nas operações com exterior é permitido informar o código do país + código da localidade + número do telefone</para>
        /// <para xml:lang="en">Pattern: [0-9]{6,20}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Número do telefone do prestador: Preencher com o Código DDD + número do telefone." +
            " Nas operações com exterior é permitido informar o código do país + código da lo" +
            "calidade + número do telefone)"))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{6,20}")]
        [System.Xml.Serialization.XmlElementAttribute("fone")]
        public string Fone { get; set; }
        
        /// <summary>
        /// <para>E-mail</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 80.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("E-mail")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(80)]
        [System.Xml.Serialization.XmlElementAttribute("email")]
        public string Email { get; set; }
    }
}
