//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCLocacaoSublocacao", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcLocacaoSublocacao
    {
        
        /// <summary>
        /// <para>Categoria do serviço</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Categoria do serviço")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("categ")]
        public TsCategoriaServico Categ { get; set; }
        
        /// <summary>
        /// <para>Tipo de objetos da locação, sublocação, arrendamento, direito de passagem ou permissão de uso</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Tipo de objetos da locação, sublocação, arrendamento, direito de passagem ou perm" +
            "issão de uso"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("objeto")]
        public TsObjetoLocacao Objeto { get; set; }
        
        /// <summary>
        /// <para>Extensão total da ferrovia, rodovia, cabos, dutos ou condutos</para>
        /// <para>Extensão total da ferrovia, rodovia, cabos, dutos ou condutos</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 5.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,5}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Extensão total da ferrovia, rodovia, cabos, dutos ou condutos")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(5)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,5}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("extensao")]
        public string Extensao { get; set; }
        
        /// <summary>
        /// <para>Número total de postes</para>
        /// <para>Número total de postes</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 6.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,6}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número total de postes")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(6)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,6}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("nPostes")]
        public string NPostes { get; set; }
    }
}
