//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCRTCTotalCBS", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcrtcTotalCbs
    {
        
        /// <summary>
        /// <para>Grupo de valores referentes ao crédito presumido para CBS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de valores referentes ao crédito presumido para CBS")]
        [System.Xml.Serialization.XmlElementAttribute("gCBSCredPres")]
        public TcrtcTotalCbsCredPres GcbsCredPres { get; set; }
        
        /// <summary>
        /// <para>Total do Diferimento CBS (vDifCBS = vCBS x pDifCBS)</para>
        /// <para>Valor decimal com 1 a 15 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Total do Diferimento CBS (vDifCBS = vCBS x pDifCBS)")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\\.[0-9]{2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("vDifCBS")]
        public string VDifCbs { get; set; }
        
        /// <summary>
        /// <para>Total valor da CBS da União (vCBS = vBC x (pCBS ou pAliqEfetCBS))</para>
        /// <para>Valor decimal com 1 a 15 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Total valor da CBS da União (vCBS = vBC x (pCBS ou pAliqEfetCBS))")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\\.[0-9]{2})?")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("vCBS")]
        public string Vcbs { get; set; }
    }
}
