//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCServ", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcServ
    {
        
        /// <summary>
        /// <para>Grupo de informações relativas ao local da prestação do serviço</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações relativas ao local da prestação do serviço")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("locPrest")]
        public TcLocPrest LocPrest { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações relativas ao código do serviço prestado</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações relativas ao código do serviço prestado")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cServ")]
        public TccServ CServ { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações relativas à exportação/importação de serviço prestado</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações relativas à exportação/importação de serviço prestado")]
        [System.Xml.Serialization.XmlElementAttribute("comExt")]
        public TcComExterior ComExt { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações relativas a atividades de Locação, sublocação, arrendamento, direito de passagem ou permissão de uso, compartilhado ou não, de ferrovia, rodovia, postes, cabos, dutos e condutos de qualquer natureza</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Grupo de informações relativas a atividades de Locação, sublocação, arrendamento," +
            " direito de passagem ou permissão de uso, compartilhado ou não, de ferrovia, rod" +
            "ovia, postes, cabos, dutos e condutos de qualquer natureza"))]
        [System.Xml.Serialization.XmlElementAttribute("lsadppu")]
        public TcLocacaoSublocacao Lsadppu { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações do DPS relativas à serviço de obra</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações do DPS relativas à serviço de obra")]
        [System.Xml.Serialization.XmlElementAttribute("obra")]
        public TcInfoObra Obra { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações do DPS relativas à Evento</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações do DPS relativas à Evento")]
        [System.Xml.Serialization.XmlElementAttribute("atvEvento")]
        public TcAtvEvento AtvEvento { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações complementares disponível para todos os serviços prestados</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações complementares disponível para todos os serviços prestados")]
        [System.Xml.Serialization.XmlElementAttribute("infoCompl")]
        public TcInfoCompl InfoCompl { get; set; }
    }
}
