//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCTribTotal", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcTribTotal
    {
        
        /// <summary>
        /// <para>Valor monetário total aproximado dos tributos, em conformidade com o artigo 1o da Lei no 12.741/2012</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Valor monetário total aproximado dos tributos, em conformidade com o artigo 1o da" +
            " Lei no 12.741/2012"))]
        [System.Xml.Serialization.XmlElementAttribute("vTotTrib")]
        public TcTribTotalMonet VTotTrib { get; set; }
        
        /// <summary>
        /// <para>Valor percentual total aproximado dos tributos, em conformidade com o artigo 1o da Lei no 12.741/2012</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Valor percentual total aproximado dos tributos, em conformidade com o artigo 1o d" +
            "a Lei no 12.741/2012"))]
        [System.Xml.Serialization.XmlElementAttribute("pTotTrib")]
        public TcTribTotalPercent PTotTrib { get; set; }
        
        /// <summary>
        /// <para>Indicador de informação de valor total de tributos. Possui valor fixo igual a zero (indTotTrib=0).
        ///              Não informar nenhum valor estimado para os Tributos (Decreto 8.264/2014).
        ///              0 - Não;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Indicador de informação de valor total de tributos. Possui valor fixo igual a zer" +
            "o (indTotTrib=0). Não informar nenhum valor estimado para os Tributos (Decreto 8" +
            ".264/2014). 0 - Não;"))]
        [System.Xml.Serialization.XmlElementAttribute("indTotTrib")]
        public TsTipoIndTotTrib IndTotTrib { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IndTotTrib property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndTotTribSpecified { get; set; }
        
        /// <summary>
        /// <para>Valor percentual aproximado do total dos tributos da alíquota do Simples Nacional (%)</para>
        /// <para>Valor decimal com 1 ou 2 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,1}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Valor percentual aproximado do total dos tributos da alíquota do Simples Nacional" +
            " (%)"))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,1}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("pTotTribSN")]
        public string PTotTribSn { get; set; }
    }
}
