//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    /// <summary>
    /// <para>Tipos de Regimes Especiais de Tributação:
    ///        0 - Nenhum;
    ///        1 - Ato Cooperado (Cooperativa);
    ///        2 - Estimativa;
    ///        3 - Microempresa Municipal;
    ///        4 - Notário ou Registrador;
    ///        5 - Profissional Autônomo;
    ///        6 - Sociedade de Profissionais;</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Tipos de Regimes Especiais de Tributação: 0 - Nenhum; 1 - Ato Cooperado (Cooperat" +
        "iva); 2 - Estimativa; 3 - Microempresa Municipal; 4 - Notário ou Registrador; 5 " +
        "- Profissional Autônomo; 6 - Sociedade de Profissionais;"))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TSRegEspTrib", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public enum TsRegEspTrib
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
    }
}
