//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    /// <summary>
    /// <para>Situações possíveis:
    ///        100 - NFS-e Gerada;
    ///        101 - NFS-e de Substituição Gerada;
    ///        102 - NFS-e de Decisão Judicial;
    ///        103 - NFS-e Avulsa;
    ///        107 - NFS-e MEI;</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Situações possíveis: 100 - NFS-e Gerada; 101 - NFS-e de Substituição Gerada; 102 " +
        "- NFS-e de Decisão Judicial; 103 - NFS-e Avulsa; 107 - NFS-e MEI;"))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TStat", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public enum TStat
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("100")]
        Item100,
        
        [System.Xml.Serialization.XmlEnumAttribute("101")]
        Item101,
        
        [System.Xml.Serialization.XmlEnumAttribute("102")]
        Item102,
        
        [System.Xml.Serialization.XmlEnumAttribute("103")]
        Item103,
        
        [System.Xml.Serialization.XmlEnumAttribute("107")]
        Item107,
    }
}
