//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    /// <summary>
    /// <para>Indicador de informação de valor total de tributos. Possui valor fixo igual a zero (indTotTrib=0).
    ///        Não informar nenhum valor estimado para os Tributos (Decreto 8.264/2014).
    ///        0 - Não;</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Indicador de informação de valor total de tributos. Possui valor fixo igual a zer" +
        "o (indTotTrib=0). Não informar nenhum valor estimado para os Tributos (Decreto 8" +
        ".264/2014). 0 - Não;"))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TSTipoIndTotTrib", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public enum TsTipoIndTotTrib
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
    }
}
