//------------------------------------------------------------------------------
// <auto-generated>
//     Este arquivo contém apenas os tipos de assinatura XML (XMLDSig) necessários
//     para manter compatibilidade com métodos legados em BaseHandler.cs
//     
//     Tipos extraídos de NfseTypes.cs para reduzir o tamanho do código legado.
//     Estes tipos são do namespace http://www.w3.org/2000/09/xmldsig#
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

/// <remarks/>

[SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRootAttribute("Signature", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class SignatureType
{

    private SignedInfoType signedInfoField;

    private SignatureValueType signatureValueField;

    private KeyInfoType keyInfoField;

    private ObjectType[] objectField;

    private string idField;

    /// <remarks/>
    public SignedInfoType SignedInfo
    {
        get
        {
            return signedInfoField;
        }
        set
        {
            signedInfoField = value;
        }
    }

    /// <remarks/>
    public SignatureValueType SignatureValue
    {
        get
        {
            return signatureValueField;
        }
        set
        {
            signatureValueField = value;
        }
    }

    /// <remarks/>
    public KeyInfoType KeyInfo
    {
        get
        {
            return keyInfoField;
        }
        set
        {
            keyInfoField = value;
        }
    }

    /// <remarks/>
    [XmlElementAttribute("Object")]
    public ObjectType[] Object
    {
        get
        {
            return objectField;
        }
        set
        {
            objectField = value;
        }
    }

    /// <remarks/>
    [XmlAttributeAttribute(DataType = "ID")]
    public string Id
    {
        get
        {
            return idField;
        }
        set
        {
            idField = value;
        }
    }
}

/// <remarks/>

[SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRootAttribute("SignedInfo", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class SignedInfoType
{

    private CanonicalizationMethodType canonicalizationMethodField;

    private SignatureMethodType signatureMethodField;

    private ReferenceType[] referenceField;

    private string idField;

    /// <remarks/>
    public CanonicalizationMethodType CanonicalizationMethod
    {
        get
        {
            return canonicalizationMethodField;
        }
        set
        {
            canonicalizationMethodField = value;
        }
    }

    /// <remarks/>
    public SignatureMethodType SignatureMethod
    {
        get
        {
            return signatureMethodField;
        }
        set
        {
            signatureMethodField = value;
        }
    }

    /// <remarks/>
    [XmlElementAttribute("Reference")]
    public ReferenceType[] Reference
    {
        get
        {
            return referenceField;
        }
        set
        {
            referenceField = value;
        }
    }

    /// <remarks/>
    [XmlAttributeAttribute(DataType = "ID")]
    public string Id
    {
        get
        {
            return idField;
        }
        set
        {
            idField = value;
        }
    }
}

/// <remarks/>

[SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRootAttribute("CanonicalizationMethod", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class CanonicalizationMethodType
{

    private System.Xml.XmlNode[] anyField;

    private string algorithmField;

    /// <remarks/>
    [XmlTextAttribute()]
    [XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any
    {
        get
        {
            return anyField;
        }
        set
        {
            anyField = value;
        }
    }

    /// <remarks/>
    [XmlAttributeAttribute(DataType = "anyURI")]
    public string Algorithm
    {
        get
        {
            return algorithmField;
        }
        set
        {
            algorithmField = value;
        }
    }
}

/// <remarks/>

[SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRootAttribute("SignatureMethod", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class SignatureMethodType
{

    private string hMACOutputLengthField;

    private System.Xml.XmlNode[] anyField;

    private string algorithmField;

    /// <remarks/>
    [XmlElementAttribute(DataType = "integer")]
    public string HMACOutputLength
    {
        get
        {
            return hMACOutputLengthField;
        }
        set
        {
            hMACOutputLengthField = value;
        }
    }

    /// <remarks/>
    [XmlTextAttribute()]
    [XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any
    {
        get
        {
            return anyField;
        }
        set
        {
            anyField = value;
        }
    }

    /// <remarks/>
    [XmlAttributeAttribute(DataType = "anyURI")]
    public string Algorithm
    {
        get
        {
            return algorithmField;
        }
        set
        {
            algorithmField = value;
        }
    }
}

/// <remarks/>

[SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRootAttribute("Reference", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class ReferenceType
{

    private TransformType[] transformsField;

    private DigestMethodType digestMethodField;

    private byte[] digestValueField;

    private string idField;

    private string uRIField;

    private string typeField;

    /// <remarks/>
    [XmlArrayItemAttribute("Transform", IsNullable = false)]
    public TransformType[] Transforms
    {
        get
        {
            return transformsField;
        }
        set
        {
            transformsField = value;
        }
    }

    /// <remarks/>
    public DigestMethodType DigestMethod
    {
        get
        {
            return digestMethodField;
        }
        set
        {
            digestMethodField = value;
        }
    }

    /// <remarks/>
    [XmlElementAttribute(DataType = "base64Binary")]
    public byte[] DigestValue
    {
        get
        {
            return digestValueField;
        }
        set
        {
            digestValueField = value;
        }
    }

    /// <remarks/>
    [XmlAttributeAttribute(DataType = "ID")]
    public string Id
    {
        get
        {
            return idField;
        }
        set
        {
            idField = value;
        }
    }

    /// <remarks/>
    [XmlAttributeAttribute(DataType = "anyURI")]
    public string URI
    {
        get
        {
            return uRIField;
        }
        set
        {
            uRIField = value;
        }
    }

    /// <remarks/>
    [XmlAttributeAttribute(DataType = "anyURI")]
    public string Type
    {
        get
        {
            return typeField;
        }
        set
        {
            typeField = value;
        }
    }
}

/// <remarks/>

[SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRootAttribute("Transform", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class TransformType
{

    private object[] itemsField;

    private string[] textField;

    private string algorithmField;

    /// <remarks/>
    [XmlAnyElementAttribute()]
    [XmlElementAttribute("XPath", typeof(string))]
    public object[] Items
    {
        get
        {
            return itemsField;
        }
        set
        {
            itemsField = value;
        }
    }

    /// <remarks/>
    [XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return textField;
        }
        set
        {
            textField = value;
        }
    }

    /// <remarks/>
    [XmlAttributeAttribute(DataType = "anyURI")]
    public string Algorithm
    {
        get
        {
            return algorithmField;
        }
        set
        {
            algorithmField = value;
        }
    }
}

/// <remarks/>

[SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRootAttribute("DigestMethod", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class DigestMethodType
{

    private System.Xml.XmlNode[] anyField;

    private string algorithmField;

    /// <remarks/>
    [XmlTextAttribute()]
    [XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any
    {
        get
        {
            return anyField;
        }
        set
        {
            anyField = value;
        }
    }

    /// <remarks/>
    [XmlAttributeAttribute(DataType = "anyURI")]
    public string Algorithm
    {
        get
        {
            return algorithmField;
        }
        set
        {
            algorithmField = value;
        }
    }
}

/// <remarks/>

[SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRootAttribute("SignatureValue", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class SignatureValueType
{

    private string idField;

    private byte[] valueField;

    /// <remarks/>
    [XmlAttributeAttribute(DataType = "ID")]
    public string Id
    {
        get
        {
            return idField;
        }
        set
        {
            idField = value;
        }
    }

    /// <remarks/>
    [XmlTextAttribute(DataType = "base64Binary")]
    public byte[] Value
    {
        get
        {
            return valueField;
        }
        set
        {
            valueField = value;
        }
    }
}

/// <remarks/>

[SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRootAttribute("KeyInfo", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class KeyInfoType
{

    private object[] itemsField;

    private ItemsChoiceType5[] itemsElementNameField;

    private string[] textField;

    private string idField;

    /// <remarks/>
    [XmlAnyElementAttribute()]
    [XmlElementAttribute("KeyName", typeof(string))]
    [XmlElementAttribute("KeyValue", typeof(KeyValueType))]
    [XmlElementAttribute("MgmtData", typeof(string))]
    [XmlElementAttribute("PGPData", typeof(PGPDataType))]
    [XmlElementAttribute("RetrievalMethod", typeof(RetrievalMethodType))]
    [XmlElementAttribute("SPKIData", typeof(SPKIDataType))]
    [XmlElementAttribute("X509Data", typeof(X509DataType))]
    [XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items
    {
        get
        {
            return itemsField;
        }
        set
        {
            itemsField = value;
        }
    }

    /// <remarks/>
    [XmlElementAttribute("ItemsElementName")]
    [XmlIgnoreAttribute()]
    public ItemsChoiceType5[] ItemsElementName
    {
        get
        {
            return itemsElementNameField;
        }
        set
        {
            itemsElementNameField = value;
        }
    }

    /// <remarks/>
    [XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return textField;
        }
        set
        {
            textField = value;
        }
    }

    /// <remarks/>
    [XmlAttributeAttribute(DataType = "ID")]
    public string Id
    {
        get
        {
            return idField;
        }
        set
        {
            idField = value;
        }
    }
}

/// <remarks/>

[SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRootAttribute("KeyValue", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class KeyValueType
{

    private object itemField;

    private string[] textField;

    /// <remarks/>
    [XmlAnyElementAttribute()]
    [XmlElementAttribute("DSAKeyValue", typeof(DSAKeyValueType))]
    [XmlElementAttribute("RSAKeyValue", typeof(RSAKeyValueType))]
    public object Item
    {
        get
        {
            return itemField;
        }
        set
        {
            itemField = value;
        }
    }

    /// <remarks/>
    [XmlTextAttribute()]
    public string[] Text
    {
        get
        {
            return textField;
        }
        set
        {
            textField = value;
        }
    }
}

/// <remarks/>

[SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRootAttribute("DSAKeyValue", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class DSAKeyValueType
{

    private byte[] pField;

    private byte[] qField;

    private byte[] gField;

    private byte[] yField;

    private byte[] jField;

    private byte[] seedField;

    private byte[] pgenCounterField;

    /// <remarks/>
    [XmlElementAttribute(DataType = "base64Binary")]
    public byte[] P
    {
        get
        {
            return pField;
        }
        set
        {
            pField = value;
        }
    }

    /// <remarks/>
    [XmlElementAttribute(DataType = "base64Binary")]
    public byte[] Q
    {
        get
        {
            return qField;
        }
        set
        {
            qField = value;
        }
    }

    /// <remarks/>
    [XmlElementAttribute(DataType = "base64Binary")]
    public byte[] G
    {
        get
        {
            return gField;
        }
        set
        {
            gField = value;
        }
    }

    /// <remarks/>
    [XmlElementAttribute(DataType = "base64Binary")]
    public byte[] Y
    {
        get
        {
            return yField;
        }
        set
        {
            yField = value;
        }
    }

    /// <remarks/>
    [XmlElementAttribute(DataType = "base64Binary")]
    public byte[] J
    {
        get
        {
            return jField;
        }
        set
        {
            jField = value;
        }
    }

    /// <remarks/>
    [XmlElementAttribute(DataType = "base64Binary")]
    public byte[] Seed
    {
        get
        {
            return seedField;
        }
        set
        {
            seedField = value;
        }
    }

    /// <remarks/>
    [XmlElementAttribute(DataType = "base64Binary")]
    public byte[] PgenCounter
    {
        get
        {
            return pgenCounterField;
        }
        set
        {
            pgenCounterField = value;
        }
    }
}

/// <remarks/>

[SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRootAttribute("RSAKeyValue", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class RSAKeyValueType
{

    private byte[] modulusField;

    private byte[] exponentField;

    /// <remarks/>
    [XmlElementAttribute(DataType = "base64Binary")]
    public byte[] Modulus
    {
        get
        {
            return modulusField;
        }
        set
        {
            modulusField = value;
        }
    }

    /// <remarks/>
    [XmlElementAttribute(DataType = "base64Binary")]
    public byte[] Exponent
    {
        get
        {
            return exponentField;
        }
        set
        {
            exponentField = value;
        }
    }
}

/// <remarks/>

[SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRootAttribute("PGPData", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class PGPDataType
{

    private object[] itemsField;

    private ItemsChoiceType4[] itemsElementNameField;

    /// <remarks/>
    [XmlAnyElementAttribute()]
    [XmlElementAttribute("PGPKeyID", typeof(byte[]), DataType = "base64Binary")]
    [XmlElementAttribute("PGPKeyPacket", typeof(byte[]), DataType = "base64Binary")]
    [XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items
    {
        get
        {
            return itemsField;
        }
        set
        {
            itemsField = value;
        }
    }

    /// <remarks/>
    [XmlElementAttribute("ItemsElementName")]
    [XmlIgnoreAttribute()]
    public ItemsChoiceType4[] ItemsElementName
    {
        get
        {
            return itemsElementNameField;
        }
        set
        {
            itemsElementNameField = value;
        }
    }
}

/// <remarks/>

[SerializableAttribute()]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#", IncludeInSchema = false)]
public enum ItemsChoiceType4
{

    /// <remarks/>
    [XmlEnumAttribute("##any:")]
    Item,

    /// <remarks/>
    PGPKeyID,

    /// <remarks/>
    PGPKeyPacket,
}

/// <remarks/>

[SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRootAttribute("RetrievalMethod", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class RetrievalMethodType
{

    private TransformType[] transformsField;

    private string uRIField;

    private string typeField;

    /// <remarks/>
    [XmlArrayItemAttribute("Transform", IsNullable = false)]
    public TransformType[] Transforms
    {
        get
        {
            return transformsField;
        }
        set
        {
            transformsField = value;
        }
    }

    /// <remarks/>
    [XmlAttributeAttribute(DataType = "anyURI")]
    public string URI
    {
        get
        {
            return uRIField;
        }
        set
        {
            uRIField = value;
        }
    }

    /// <remarks/>
    [XmlAttributeAttribute(DataType = "anyURI")]
    public string Type
    {
        get
        {
            return typeField;
        }
        set
        {
            typeField = value;
        }
    }
}

/// <remarks/>

[SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRootAttribute("SPKIData", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class SPKIDataType
{

    private byte[][] sPKISexpField;

    private System.Xml.XmlElement anyField;

    /// <remarks/>
    [XmlElementAttribute("SPKISexp", DataType = "base64Binary")]
    public byte[][] SPKISexp
    {
        get
        {
            return sPKISexpField;
        }
        set
        {
            sPKISexpField = value;
        }
    }

    /// <remarks/>
    [XmlAnyElementAttribute()]
    public System.Xml.XmlElement Any
    {
        get
        {
            return anyField;
        }
        set
        {
            anyField = value;
        }
    }
}

/// <remarks/>

[SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRootAttribute("X509Data", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class X509DataType
{

    private object[] itemsField;

    private ItemsChoiceType3[] itemsElementNameField;

    /// <remarks/>
    [XmlAnyElementAttribute()]
    [XmlElementAttribute("X509CRL", typeof(byte[]), DataType = "base64Binary")]
    [XmlElementAttribute("X509Certificate", typeof(byte[]), DataType = "base64Binary")]
    [XmlElementAttribute("X509IssuerSerial", typeof(X509IssuerSerialType))]
    [XmlElementAttribute("X509SKI", typeof(byte[]), DataType = "base64Binary")]
    [XmlElementAttribute("X509SubjectName", typeof(string))]
    [XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items
    {
        get
        {
            return itemsField;
        }
        set
        {
            itemsField = value;
        }
    }

    /// <remarks/>
    [XmlElementAttribute("ItemsElementName")]
    [XmlIgnoreAttribute()]
    public ItemsChoiceType3[] ItemsElementName
    {
        get
        {
            return itemsElementNameField;
        }
        set
        {
            itemsElementNameField = value;
        }
    }
}

/// <remarks/>

[SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class X509IssuerSerialType
{

    private string x509IssuerNameField;

    private string x509SerialNumberField;

    /// <remarks/>
    public string X509IssuerName
    {
        get
        {
            return x509IssuerNameField;
        }
        set
        {
            x509IssuerNameField = value;
        }
    }

    /// <remarks/>
    [XmlElementAttribute(DataType = "integer")]
    public string X509SerialNumber
    {
        get
        {
            return x509SerialNumberField;
        }
        set
        {
            x509SerialNumberField = value;
        }
    }
}

/// <remarks/>

[SerializableAttribute()]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#", IncludeInSchema = false)]
public enum ItemsChoiceType3
{

    /// <remarks/>
    [XmlEnumAttribute("##any:")]
    Item,

    /// <remarks/>
    X509CRL,

    /// <remarks/>
    X509Certificate,

    /// <remarks/>
    X509IssuerSerial,

    /// <remarks/>
    X509SKI,

    /// <remarks/>
    X509SubjectName,
}

/// <remarks/>

[SerializableAttribute()]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#", IncludeInSchema = false)]
public enum ItemsChoiceType5
{

    /// <remarks/>
    [XmlEnumAttribute("##any:")]
    Item,

    /// <remarks/>
    KeyName,

    /// <remarks/>
    KeyValue,

    /// <remarks/>
    MgmtData,

    /// <remarks/>
    PGPData,

    /// <remarks/>
    RetrievalMethod,

    /// <remarks/>
    SPKIData,

    /// <remarks/>
    X509Data,
}

/// <remarks/>

[SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRootAttribute("Object", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class ObjectType
{

    private System.Xml.XmlNode[] anyField;

    private string idField;

    private string mimeTypeField;

    private string encodingField;

    /// <remarks/>
    [XmlTextAttribute()]
    [XmlAnyElementAttribute()]
    public System.Xml.XmlNode[] Any
    {
        get
        {
            return anyField;
        }
        set
        {
            anyField = value;
        }
    }

    /// <remarks/>
    [XmlAttributeAttribute(DataType = "ID")]
    public string Id
    {
        get
        {
            return idField;
        }
        set
        {
            idField = value;
        }
    }

    /// <remarks/>
    [XmlAttributeAttribute()]
    public string MimeType
    {
        get
        {
            return mimeTypeField;
        }
        set
        {
            mimeTypeField = value;
        }
    }

    /// <remarks/>
    [XmlAttributeAttribute(DataType = "anyURI")]
    public string Encoding
    {
        get
        {
            return encodingField;
        }
        set
        {
            encodingField = value;
        }
    }
}
