//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ConsultarNfseFaixaEnvioFaixa", Namespace="http://www.sped.fazenda.gov.br/nfse", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarNfseFaixaEnvioFaixa
    {
        
        /// <summary>
        /// <para>Tipo Número sequencial do documento</para>
        /// <para xml:lang="en">Maximum length: 13.</para>
        /// <para xml:lang="en">Pattern: [1-9]{1}[0-9]{0,12}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(13)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]{1}[0-9]{0,12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("NumeroNfseInicial")]
        public string NumeroNfseInicial { get; set; }
        
        /// <summary>
        /// <para>Tipo Número sequencial do documento</para>
        /// <para xml:lang="en">Maximum length: 13.</para>
        /// <para xml:lang="en">Pattern: [1-9]{1}[0-9]{0,12}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(13)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]{1}[0-9]{0,12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("NumeroNfseFinal")]
        public string NumeroNfseFinal { get; set; }
    }
}
