//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EnviarLoteDpsSincronoResposta", Namespace="http://www.sped.fazenda.gov.br/nfse", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("EnviarLoteDpsSincronoResposta", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public partial class EnviarLoteDpsSincronoResposta
    {
        
        /// <summary>
        /// <para>Número com 15 dígitos</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// <para xml:lang="en">Pattern: [0-9]{15}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{15}")]
        [System.Xml.Serialization.XmlElementAttribute("NumeroLote")]
        public string NumeroLote { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DataRecebimento", DataType="dateTime")]
        public System.DateTime DataRecebimento { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the DataRecebimento property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DataRecebimentoSpecified { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Maximum length: 50.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(50)]
        [System.Xml.Serialization.XmlElementAttribute("Protocolo")]
        public string Protocolo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ListaNfse")]
        public EnviarLoteDpsSincronoRespostaListaNfse ListaNfse { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TcMensagemRetorno> _listaMensagemRetorno;
        
        [System.Xml.Serialization.XmlArrayAttribute("ListaMensagemRetorno")]
        [System.Xml.Serialization.XmlArrayItemAttribute("MensagemRetorno", Namespace="http://www.sped.fazenda.gov.br/nfse")]
        public System.Collections.ObjectModel.Collection<TcMensagemRetorno> ListaMensagemRetorno
        {
            get
            {
                return _listaMensagemRetorno;
            }
            private set
            {
                _listaMensagemRetorno = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ListaMensagemRetorno collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListaMensagemRetornoSpecified
        {
            get
            {
                return (this.ListaMensagemRetorno.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="EnviarLoteDpsSincronoResposta" /> class.</para>
        /// </summary>
        public EnviarLoteDpsSincronoResposta()
        {
            this._listaMensagemRetorno = new System.Collections.ObjectModel.Collection<TcMensagemRetorno>();
            this._listaMensagemRetornoLote = new System.Collections.ObjectModel.Collection<TcMensagemRetornoLote>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TcMensagemRetornoLote> _listaMensagemRetornoLote;
        
        [System.Xml.Serialization.XmlArrayAttribute("ListaMensagemRetornoLote")]
        [System.Xml.Serialization.XmlArrayItemAttribute("MensagemRetorno", Namespace="http://www.sped.fazenda.gov.br/nfse")]
        public System.Collections.ObjectModel.Collection<TcMensagemRetornoLote> ListaMensagemRetornoLote
        {
            get
            {
                return _listaMensagemRetornoLote;
            }
            private set
            {
                _listaMensagemRetornoLote = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ListaMensagemRetornoLote collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListaMensagemRetornoLoteSpecified
        {
            get
            {
                return (this.ListaMensagemRetornoLote.Count != 0);
            }
        }
    }
}
