//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ReferenceType", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Reference", Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class ReferenceType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TransformType> _transforms;
        
        [System.Xml.Serialization.XmlArrayAttribute("Transforms")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public System.Collections.ObjectModel.Collection<TransformType> Transforms
        {
            get
            {
                return _transforms;
            }
            private set
            {
                _transforms = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Transforms collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransformsSpecified
        {
            get
            {
                return (this.Transforms.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ReferenceType" /> class.</para>
        /// </summary>
        public ReferenceType()
        {
            this._transforms = new System.Collections.ObjectModel.Collection<TransformType>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DigestMethod")]
        public DigestMethodType DigestMethod { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DigestValue", DataType="base64Binary")]
        public byte[] DigestValue { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Id")]
        public string Id { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("URI")]
        public string Uri { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Type")]
        public string Type { get; set; }
    }
}
