//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tcCadastro", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Cadastro", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public partial class TcCadastro
    {
        
        /// <summary>
        /// <para>Tipo Número do CNPJ</para>
        /// <para xml:lang="en">Minimum length: 14.</para>
        /// <para xml:lang="en">Maximum length: 14.</para>
        /// <para xml:lang="en">Pattern: [0-9]{14}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(14)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(14)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{14}")]
        [System.Xml.Serialization.XmlElementAttribute("CNPJ")]
        public string Cnpj { get; set; }
        
        /// <summary>
        /// <para>Tipo Número do CPF</para>
        /// <para xml:lang="en">Maximum length: 11.</para>
        /// <para xml:lang="en">Pattern: [0-9]{11}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{11}")]
        [System.Xml.Serialization.XmlElementAttribute("CPF")]
        public string Cpf { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("IM")]
        public string Im { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 600.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(600)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("StatusCadastro")]
        public string StatusCadastro { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 300.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(300)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xNome")]
        public string XNome { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 150.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(150)]
        [System.Xml.Serialization.XmlElementAttribute("xFant")]
        public string XFant { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("enderNac")]
        public TcEnderecoEmitente EnderNac { get; set; }
        
        /// <summary>
        /// <para>Número do telefone do prestador:
        ///        Preencher com o Código DDD + número do telefone.
        ///        Nas operações com exterior é permitido informar o código do país + código da localidade + número do telefone</para>
        /// <para xml:lang="en">Pattern: [0-9]{6,20}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{6,20}")]
        [System.Xml.Serialization.XmlElementAttribute("fone")]
        public string Fone { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 80.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(80)]
        [System.Xml.Serialization.XmlElementAttribute("email")]
        public string Email { get; set; }
        
        /// <summary>
        /// <para>Sim ou Não
        ///        1 - Sim; 
        ///        2 - Nao.</para>
        /// <para xml:lang="en">Pattern: 1|2.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("1|2")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("EmiteNfse")]
        public sbyte EmiteNfse { get; set; }
        
        /// <summary>
        /// <para>Sim ou Não
        ///        1 - Sim; 
        ///        2 - Nao.</para>
        /// <para xml:lang="en">Pattern: 1|2.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("1|2")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PermiteOutrasDeducoes")]
        public sbyte PermiteOutrasDeducoes { get; set; }
        
        /// <summary>
        /// <para>Sim ou Não
        ///        1 - Sim; 
        ///        2 - Nao.</para>
        /// <para xml:lang="en">Pattern: 1|2.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("1|2")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PermiteDescontoCondicionado")]
        public sbyte PermiteDescontoCondicionado { get; set; }
        
        /// <summary>
        /// <para>Sim ou Não
        ///        1 - Sim; 
        ///        2 - Nao.</para>
        /// <para xml:lang="en">Pattern: 1|2.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("1|2")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PermiteDescontoIncondicionado")]
        public sbyte PermiteDescontoIncondicionado { get; set; }
        
        /// <summary>
        /// <para>Sim ou Não
        ///        1 - Sim; 
        ///        2 - Nao.</para>
        /// <para xml:lang="en">Pattern: 1|2.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("1|2")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PermiteExigibilidadeSuspensaDecisaoJudicial")]
        public sbyte PermiteExigibilidadeSuspensaDecisaoJudicial { get; set; }
        
        /// <summary>
        /// <para>Sim ou Não
        ///        1 - Sim; 
        ///        2 - Nao.</para>
        /// <para xml:lang="en">Pattern: 1|2.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("1|2")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PermiteExigibilidadeSuspensaProcAdm")]
        public sbyte PermiteExigibilidadeSuspensaProcAdm { get; set; }
        
        /// <summary>
        /// <para>Sim ou Não
        ///        1 - Sim; 
        ///        2 - Nao.</para>
        /// <para xml:lang="en">Pattern: 1|2.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("1|2")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("PermiteTributarFora")]
        public sbyte PermiteTributarFora { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("OpcaoSimplesNacional")]
        public TcOpcaoSimplesNacional OpcaoSimplesNacional { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("OpcaoMei")]
        public TcOpcaoMei OpcaoMei { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TcAtividade> _atividades;
        
        [System.Xml.Serialization.XmlArrayAttribute("Atividades")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Atividade", Namespace="http://www.sped.fazenda.gov.br/nfse")]
        public System.Collections.ObjectModel.Collection<TcAtividade> Atividades
        {
            get
            {
                return _atividades;
            }
            private set
            {
                _atividades = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Atividades collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AtividadesSpecified
        {
            get
            {
                return (this.Atividades.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TcCadastro" /> class.</para>
        /// </summary>
        public TcCadastro()
        {
            this._atividades = new System.Collections.ObjectModel.Collection<TcAtividade>();
            this._tributacoesPermitidas = new System.Collections.ObjectModel.Collection<TsTribIssqn>();
            this._pessoasAutorizadas = new System.Collections.ObjectModel.Collection<TcPessoasAutorizada>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TsTribIssqn> _tributacoesPermitidas;
        
        [System.Xml.Serialization.XmlArrayAttribute("TributacoesPermitidas")]
        [System.Xml.Serialization.XmlArrayItemAttribute("tribISSQN", Namespace="http://www.sped.fazenda.gov.br/nfse")]
        public System.Collections.ObjectModel.Collection<TsTribIssqn> TributacoesPermitidas
        {
            get
            {
                return _tributacoesPermitidas;
            }
            private set
            {
                _tributacoesPermitidas = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the TributacoesPermitidas collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TributacoesPermitidasSpecified
        {
            get
            {
                return (this.TributacoesPermitidas.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TcPessoasAutorizada> _pessoasAutorizadas;
        
        [System.Xml.Serialization.XmlArrayAttribute("PessoasAutorizadas")]
        [System.Xml.Serialization.XmlArrayItemAttribute("PessoasAutorizada", Namespace="http://www.sped.fazenda.gov.br/nfse")]
        public System.Collections.ObjectModel.Collection<TcPessoasAutorizada> PessoasAutorizadas
        {
            get
            {
                return _pessoasAutorizadas;
            }
            private set
            {
                _pessoasAutorizadas = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the PessoasAutorizadas collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PessoasAutorizadasSpecified
        {
            get
            {
                return (this.PessoasAutorizadas.Count != 0);
            }
        }
    }
}
