//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCInfDPS", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcInfDps
    {
        
        /// <summary>
        /// <para>Identificação do Ambiente: 
        ///            1 - Produção;
        ///            2 - Homologação</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Identificação do Ambiente: 1 - Produção; 2 - Homologação")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("tpAmb")]
        public TsTipoAmbiente TpAmb { get; set; }
        
        /// <summary>
        /// <para>Data e hora da emissão do DPS. Data e hora no formato UTC (Universal Coordinated Time): AAAA-MM-DDThh:mm:ssTZD</para>
        /// <para>Data e Hora, formato UTC (AAAA-MM-DDThh:mm:ssTZD, onde TZD = +hh:mm ou -hh:mm)</para>
        /// <para xml:lang="en">Pattern: (((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30)))))T(20|21|22|23|[0-1]\d):[0-5]\d:[0-5]\d([\-,\+](0[0-9]|10|11):00|([\+](12):00)).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Data e hora da emissão do DPS. Data e hora no formato UTC (Universal Coordinated " +
            "Time): AAAA-MM-DDThh:mm:ssTZD"))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute(("(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-" +
            "((0[1-9])|(1\\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29" +
            "|30)))))T(20|21|22|23|[0-1]\\d):[0-5]\\d:[0-5]\\d([\\-,\\+](0[0-9]|10|11):00|([\\+](12" +
            "):00))"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dhEmi")]
        public string DhEmi { get; set; }
        
        /// <summary>
        /// <para>Versão do aplicativo que gerou o DPS</para>
        /// <para>Tipo Versão do Aplicativo que gerou o documento fiscal</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Versão do aplicativo que gerou o DPS")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(20)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("verAplic")]
        public string VerAplic { get; set; }
        
        /// <summary>
        /// <para>Número do equipamento emissor do DPS ou série do DPS</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 5.</para>
        /// <para xml:lang="en">Pattern: [0-9]{1,5}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número do equipamento emissor do DPS ou série do DPS")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(5)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{1,5}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("serie")]
        public string Serie { get; set; }
        
        /// <summary>
        /// <para>Número do DPS</para>
        /// <para>Tipo Número do DPS</para>
        /// <para xml:lang="en">Maximum length: 15.</para>
        /// <para xml:lang="en">Pattern: [1-9]{1}[0-9]{0,14}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número do DPS")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]{1}[0-9]{0,14}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("nDPS")]
        public string Ndps { get; set; }
        
        /// <summary>
        /// <para>Data em que se iniciou a prestação do serviço: Dia, mês e ano (AAAAMMDD)</para>
        /// <para>Tipo data no formato AAAA-MM-DD</para>
        /// <para xml:lang="en">Pattern: (((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30))))).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Data em que se iniciou a prestação do serviço: Dia, mês e ano (AAAAMMDD)")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute(("(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-" +
            "((0[1-9])|(1\\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29" +
            "|30)))))"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dCompet")]
        public string DCompet { get; set; }
        
        /// <summary>
        /// <para>Emitente da DPS: 
        ///            1 - Prestador;</para>
        /// <para><!-- 
        ///            2 - Tomador; 
        ///            3 - Intermediário --></para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Emitente da DPS: 1 - Prestador; <!-- 2 - Tomador; 3 - Intermediário -->")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("tpEmit")]
        public TsEmitenteDps TpEmit { get; set; }
        
        /// <summary>
        /// <para>O código de município utilizado pelo Sistema Nacional NFS-e é o código definido para cada município pertencente ao ""Anexo V – Tabela de Código de Municípios do IBGE"", que consta ao final do Manual de Orientação ao Contribuinte do ISSQN para a Sefin Nacional NFS-e.
        ///            O município emissor da NFS-e é aquele município em que o emitente da DPS está cadastrado e autorizado a "emitir uma NFS-e", ou seja, emitir uma DPS para que o sistema nacional valide as informações nela prestadas e gere a NFS-e correspondente para o emitente.
        ///            Para que o sistema nacional emita a NFS-e o município emissor deve ser conveniado e estar ativo no sistema nacional. Além disso o convênio do município deve permitir que os contribuintes do município utilize os emissores públicos do Sistema Nacional NFS-e</para>
        /// <para>Tipo Código do Município segundo tabela IBGE</para>
        /// <para xml:lang="en">Pattern: [0-9]{7}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"O código de município utilizado pelo Sistema Nacional NFS-e é o código definido para cada município pertencente ao """"Anexo V – Tabela de Código de Municípios do IBGE"""", que consta ao final do Manual de Orientação ao Contribuinte do ISSQN para a Sefin Nacional NFS-e. O município emissor da NFS-e é aquele município em que o emitente da DPS está cadastrado e autorizado a ""emitir uma NFS-e"", ou seja, emitir uma DPS para que o sistema nacional valide as informações nela prestadas e gere a NFS-e correspondente para o emitente. Para que o sistema nacional emita a NFS-e o município emissor deve ser conveniado e estar ativo no sistema nacional. Além disso o convênio do município deve permitir que os contribuintes do município utilize os emissores públicos do Sistema Nacional NFS-e")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{7}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cLocEmi")]
        public string CLocEmi { get; set; }
        
        /// <summary>
        /// <para>Dados da NFS-e a ser substituída</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Dados da NFS-e a ser substituída")]
        [System.Xml.Serialization.XmlElementAttribute("subst")]
        public TcSubstituicao Subst { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações do DPS relativas ao Prestador de Serviços</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações do DPS relativas ao Prestador de Serviços")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("prest")]
        public TcInfoPrestador Prest { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações do DPS relativas ao Tomador de Serviços</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações do DPS relativas ao Tomador de Serviços")]
        [System.Xml.Serialization.XmlElementAttribute("toma")]
        public TcInfoPessoa Toma { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações do DPS relativas ao Intermediário de Serviços</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações do DPS relativas ao Intermediário de Serviços")]
        [System.Xml.Serialization.XmlElementAttribute("interm")]
        public TcInfoPessoa Interm { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações do DPS relativas ao Serviço Prestado</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações do DPS relativas ao Serviço Prestado")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("serv")]
        public TcServ Serv { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações relativas à valores do serviço prestado</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações relativas à valores do serviço prestado")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("valores")]
        public TcInfoValores Valores { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações declaradas pelo emitente referentes ao IBS e à CBS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações declaradas pelo emitente referentes ao IBS e à CBS")]
        [System.Xml.Serialization.XmlElementAttribute("IBSCBS")]
        public TcrtcInfoIbscbs Ibscbs { get; set; }
        
        /// <summary>
        /// <para>Informar o identificador precedido do literal ‘DPS’. A regra de formação do identificador de 45 posições da DPS é:
        ///        "DPS" + Cód.Mun (7) + Tipo de Inscrição Federal (1) + Inscrição Federal (14 - CPF completar com 000 à esquerda) + Série DPS (5)+ Núm. DPS (15)</para>
        /// <para xml:lang="en">Maximum length: 45.</para>
        /// <para xml:lang="en">Pattern: DPS[0-9]{42}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(45)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("DPS[0-9]{42}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Id")]
        public string Id { get; set; }
    }
}
