//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCInfNFSe", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcInfNfSe
    {
        
        /// <summary>
        /// <para>Descrição do código do IBGE do município emissor da NFS-e.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 150.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Descrição do código do IBGE do município emissor da NFS-e.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(150)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xLocEmi")]
        public string XLocEmi { get; set; }
        
        /// <summary>
        /// <para>Descrição do local da prestação do serviço.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 150.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Descrição do local da prestação do serviço.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(150)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xLocPrestacao")]
        public string XLocPrestacao { get; set; }
        
        /// <summary>
        /// <para>Número sequencial por tipo de emitente da NFS-e.</para>
        /// <para>Tipo Número sequencial do documento</para>
        /// <para xml:lang="en">Maximum length: 13.</para>
        /// <para xml:lang="en">Pattern: [1-9]{1}[0-9]{0,12}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número sequencial por tipo de emitente da NFS-e.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(13)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]{1}[0-9]{0,12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("nNFSe")]
        public string NnfSe { get; set; }
        
        /// <summary>
        /// <para>O código de município utilizado pelo Sistema Nacional NFS-e é o código definido para cada município pertencente ao ""Anexo V – Tabela de Código de Municípios do IBGE"", que consta ao final do Manual de Orientação ao Contribuinte do ISSQN para a Sefin Nacional NFS-e.
        ///            O município de incidência do ISSQN é determinado automaticamente pelo sistema, conforme regras do aspecto espacial da lei complementar federal (LC 116/03) que são válidas para todos  os municípios.
        ///            http://www.planalto.gov.br/ccivil_03/Leis/LCP/Lcp116.htm</para>
        /// <para>Tipo Código do Município segundo tabela IBGE</para>
        /// <para xml:lang="en">Pattern: [0-9]{7}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"O código de município utilizado pelo Sistema Nacional NFS-e é o código definido para cada município pertencente ao """"Anexo V – Tabela de Código de Municípios do IBGE"""", que consta ao final do Manual de Orientação ao Contribuinte do ISSQN para a Sefin Nacional NFS-e. O município de incidência do ISSQN é determinado automaticamente pelo sistema, conforme regras do aspecto espacial da lei complementar federal (LC 116/03) que são válidas para todos os municípios. http://www.planalto.gov.br/ccivil_03/Leis/LCP/Lcp116.htm")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{7}")]
        [System.Xml.Serialization.XmlElementAttribute("cLocIncid")]
        public string CLocIncid { get; set; }
        
        /// <summary>
        /// <para>A descrição do código de município utilizado pelo Sistema Nacional NFS-e é o nome de cada município pertencente ao "Anexo V – Tabela de Código de Municípios do IBGE", que consta ao final do Manual de Orientação ao Contribuinte do ISSQN para a Sefin Nacional NFS-e.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 150.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(@"A descrição do código de município utilizado pelo Sistema Nacional NFS-e é o nome de cada município pertencente ao ""Anexo V – Tabela de Código de Municípios do IBGE"", que consta ao final do Manual de Orientação ao Contribuinte do ISSQN para a Sefin Nacional NFS-e.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(150)]
        [System.Xml.Serialization.XmlElementAttribute("xLocIncid")]
        public string XLocIncid { get; set; }
        
        /// <summary>
        /// <para>Descrição do código de tributação nacional do ISSQN.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 600.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Descrição do código de tributação nacional do ISSQN.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(600)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xTribNac")]
        public string XTribNac { get; set; }
        
        /// <summary>
        /// <para>Descrição do código de tributação municipal do ISSQN.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 600.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Descrição do código de tributação municipal do ISSQN.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(600)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xTribMun")]
        public string XTribMun { get; set; }
        
        /// <summary>
        /// <para>Descrição do código da NBS.</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 600.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Descrição do código da NBS.")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(600)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xNBS")]
        public string Xnbs { get; set; }
        
        /// <summary>
        /// <para>Tipo Versão do Aplicativo que gerou o documento fiscal</para>
        /// <para>Tipo Versão do Aplicativo que gerou o documento fiscal</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 20.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tipo Versão do Aplicativo que gerou o documento fiscal")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(20)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("verAplic")]
        public string VerAplic { get; set; }
        
        /// <summary>
        /// <para>Tipo Ambiente Gerador de NFS-e:
        ///            1 - Prefeitura;
        ///            2 - Sistema Nacional da NFS-e;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Tipo Ambiente Gerador de NFS-e: 1 - Prefeitura; 2 - Sistema Nacional da NFS-e;")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ambGer")]
        public TsAmbGeradorNfSe AmbGer { get; set; }
        
        /// <summary>
        /// <para>Tipo de emissão da NFS-e:
        ///            1 - Emissão normal no modelo da NFS-e Nacional;
        ///            2 - Emissão original em leiaute próprio do município com transcrição para o modelo da NFS-e Nacional.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Tipo de emissão da NFS-e: 1 - Emissão normal no modelo da NFS-e Nacional; 2 - Emi" +
            "ssão original em leiaute próprio do município com transcrição para o modelo da N" +
            "FS-e Nacional."))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("tpEmis")]
        public TsTipoEmissao TpEmis { get; set; }
        
        /// <summary>
        /// <para>Processo de Emissão da DPS:
        ///            1 - Emissão com aplicativo do contribuinte (via Web Service);
        ///            2 - Emissão com aplicativo disponibilizado pelo fisco (Web);
        ///            3 - Emissão com aplicativo disponibilizado pelo fisco (App);</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Processo de Emissão da DPS: 1 - Emissão com aplicativo do contribuinte (via Web S" +
            "ervice); 2 - Emissão com aplicativo disponibilizado pelo fisco (Web); 3 - Emissã" +
            "o com aplicativo disponibilizado pelo fisco (App);"))]
        [System.Xml.Serialization.XmlElementAttribute("procEmi")]
        public TsProcEmissao ProcEmi { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ProcEmi property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProcEmiSpecified { get; set; }
        
        /// <summary>
        /// <para>Situações possíveis:
        ///            100 - NFS-e Gerada;
        ///            101 - NFS-e de Substituição Gerada;
        ///            102 - NFS-e de Decisão Judicial;
        ///            103 - NFS-e Avulsa;
        ///            107 - NFS-e MEI;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Situações possíveis: 100 - NFS-e Gerada; 101 - NFS-e de Substituição Gerada; 102 " +
            "- NFS-e de Decisão Judicial; 103 - NFS-e Avulsa; 107 - NFS-e MEI;"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("cStat")]
        public TStat CStat { get; set; }
        
        /// <summary>
        /// <para>Data/Hora da validação da DPS e geração da NFS-e. Data e hora no formato UTC (Universal Coordinated Time):AAAA-MM-DDThh:mm:ssTZD</para>
        /// <para>Data e Hora, formato UTC (AAAA-MM-DDThh:mm:ssTZD, onde TZD = +hh:mm ou -hh:mm)</para>
        /// <para xml:lang="en">Pattern: (((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-((0[1-9])|(1\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29|30)))))T(20|21|22|23|[0-1]\d):[0-5]\d:[0-5]\d([\-,\+](0[0-9]|10|11):00|([\+](12):00)).</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Data/Hora da validação da DPS e geração da NFS-e. Data e hora no formato UTC (Uni" +
            "versal Coordinated Time):AAAA-MM-DDThh:mm:ssTZD"))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute(("(((20(([02468][048])|([13579][26]))-02-29))|(20[0-9][0-9])-((((0[1-9])|(1[0-2]))-" +
            "((0[1-9])|(1\\d)|(2[0-8])))|((((0[13578])|(1[02]))-31)|(((0[1,3-9])|(1[0-2]))-(29" +
            "|30)))))T(20|21|22|23|[0-1]\\d):[0-5]\\d:[0-5]\\d([\\-,\\+](0[0-9]|10|11):00|([\\+](12" +
            "):00))"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("dhProc")]
        public string DhProc { get; set; }
        
        /// <summary>
        /// <para>Número sequencial do documento gerado por ambiente gerador de DFSe do múnicípio.</para>
        /// <para>Tipo Número do DFS-e</para>
        /// <para xml:lang="en">Maximum length: 13.</para>
        /// <para xml:lang="en">Pattern: [1-9]{1}[0-9]{0,12}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número sequencial do documento gerado por ambiente gerador de DFSe do múnicípio.")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(13)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[1-9]{1}[0-9]{0,12}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("nDFSe")]
        public string NdfSe { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações da DPS relativas ao emitente da NFS-e</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações da DPS relativas ao emitente da NFS-e")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("emit")]
        public TcEmitente Emit { get; set; }
        
        /// <summary>
        /// <para>Grupo de valores referentes ao Serviço Prestado</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de valores referentes ao Serviço Prestado")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("valores")]
        public TcValoresNfSe Valores { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações geradas pelo sistema referentes ao IBS e à CBS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações geradas pelo sistema referentes ao IBS e à CBS")]
        [System.Xml.Serialization.XmlElementAttribute("IBSCBS")]
        public Tcrtcibscbs Ibscbs { get; set; }
        
        /// <summary>
        /// <para>Grupo de informações da DPS relativas ao serviço prestado</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Grupo de informações da DPS relativas ao serviço prestado")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DPS")]
        public Tcdps Dps { get; set; }
        
        /// <summary>
        /// <para>Informar o identificador precedido do literal ‘NFS’. A regra de formação do identificador de 53 posições da NFS-e é:
        ///        "NFS" + Cód.Mun.(7) + Amb.Ger.(1) + Tipo de Inscrição Federal(1) + Inscrição Federal(14) + No.NFS-e(13) + AnoMes Emis.(4) + Cód.Num.(9) + DV(1)</para>
        /// <para xml:lang="en">Maximum length: 53.</para>
        /// <para xml:lang="en">Pattern: NFS[0-9]{50}.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(53)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("NFS[0-9]{50}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Id")]
        public string Id { get; set; }
    }
}
