//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCInfoDedRed", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcInfoDedRed
    {
        
        /// <summary>
        /// <para>Valor percentual padrão para dedução/redução do valor do serviço</para>
        /// <para>Valor decimal com 1 a 3 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,2}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor percentual padrão para dedução/redução do valor do serviço")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,2}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("pDR")]
        public string Pdr { get; set; }
        
        /// <summary>
        /// <para>Valor monetário padrão para dedução/redução do valor do serviço</para>
        /// <para>Valor decimal com 1 a 15 dígitos mais 2 casas decimais</para>
        /// <para xml:lang="en">Pattern: 0|0\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\.[0-9]{2})?.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Valor monetário padrão para dedução/redução do valor do serviço")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("0|0\\.[0-9]{2}|[1-9]{1}[0-9]{0,14}(\\.[0-9]{2})?")]
        [System.Xml.Serialization.XmlElementAttribute("vDR")]
        public string Vdr { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TcDocDedRed> _documentos;
        
        /// <summary>
        /// <para>Grupo de informações de documento utilizado para Dedução/Redução do valor do serviço</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Grupo de informações de documento utilizado para Dedução/Redução do valor do serv" +
            "iço"))]
        [System.Xml.Serialization.XmlArrayAttribute("documentos")]
        [System.Xml.Serialization.XmlArrayItemAttribute("docDedRed", Namespace="http://www.sped.fazenda.gov.br/nfse")]
        public System.Collections.ObjectModel.Collection<TcDocDedRed> Documentos
        {
            get
            {
                return _documentos;
            }
            private set
            {
                _documentos = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Documentos collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentosSpecified
        {
            get
            {
                return (this.Documentos.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TcInfoDedRed" /> class.</para>
        /// </summary>
        public TcInfoDedRed()
        {
            this._documentos = new System.Collections.ObjectModel.Collection<TcDocDedRed>();
        }
    }
}
