//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("tcPessoasAutorizadas", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcPessoasAutorizadas
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TcPessoasAutorizada> _pessoasAutorizada;
        
        [System.Xml.Serialization.XmlElementAttribute("PessoasAutorizada")]
        public System.Collections.ObjectModel.Collection<TcPessoasAutorizada> PessoasAutorizada
        {
            get
            {
                return _pessoasAutorizada;
            }
            private set
            {
                _pessoasAutorizada = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the PessoasAutorizada collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PessoasAutorizadaSpecified
        {
            get
            {
                return (this.PessoasAutorizada.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TcPessoasAutorizadas" /> class.</para>
        /// </summary>
        public TcPessoasAutorizadas()
        {
            this._pessoasAutorizada = new System.Collections.ObjectModel.Collection<TcPessoasAutorizada>();
        }
    }
}
