//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCRTCInfoReeRepRes", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcrtcInfoReeRepRes
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TcrtcListaDoc> _documentos;
        
        /// <summary>
        /// <para>Grupo relativo aos documentos referenciados nos casos de reembolso, repasse e ressarcimento que serão 
        ///            considerados na base de cálculo do ISSQN, do IBS e da CBS</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Grupo relativo aos documentos referenciados nos casos de reembolso, repasse e res" +
            "sarcimento que serão considerados na base de cálculo do ISSQN, do IBS e da CBS"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("documentos")]
        public System.Collections.ObjectModel.Collection<TcrtcListaDoc> Documentos
        {
            get
            {
                return _documentos;
            }
            private set
            {
                _documentos = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="TcrtcInfoReeRepRes" /> class.</para>
        /// </summary>
        public TcrtcInfoReeRepRes()
        {
            this._documentos = new System.Collections.ObjectModel.Collection<TcrtcListaDoc>();
        }
    }
}
