//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TCRTCListaDocFornec", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TcrtcListaDocFornec
    {
        
        /// <summary>
        /// <para>Número da inscrição no Cadastro Nacional de Pessoa Jurídica (CNPJ) do Fornecedor do serviço</para>
        /// <para>Tipo Número do CNPJ</para>
        /// <para xml:lang="en">Minimum length: 14.</para>
        /// <para xml:lang="en">Maximum length: 14.</para>
        /// <para xml:lang="en">Pattern: [0-9]{14}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Número da inscrição no Cadastro Nacional de Pessoa Jurídica (CNPJ) do Fornecedor " +
            "do serviço"))]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(14)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(14)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{14}")]
        [System.Xml.Serialization.XmlElementAttribute("CNPJ")]
        public string Cnpj { get; set; }
        
        /// <summary>
        /// <para>Número da inscrição no Cadastro de Pessoa Física (CPF) do Fornecedor do serviço</para>
        /// <para>Tipo Número do CPF</para>
        /// <para xml:lang="en">Maximum length: 11.</para>
        /// <para xml:lang="en">Pattern: [0-9]{11}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Número da inscrição no Cadastro de Pessoa Física (CPF) do Fornecedor do serviço")]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{11}")]
        [System.Xml.Serialization.XmlElementAttribute("CPF")]
        public string Cpf { get; set; }
        
        /// <summary>
        /// <para>Este elemento só deverá ser preenchido para fornecedores não residentes no Brasil</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 40.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Este elemento só deverá ser preenchido para fornecedores não residentes no Brasil")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(40)]
        [System.Xml.Serialization.XmlElementAttribute("NIF")]
        public string Nif { get; set; }
        
        /// <summary>
        /// <para>Motivo para não informação do NIF:
        ///              1 - Dispensado do NIF;
        ///              2 - Não exigência do NIF;</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Motivo para não informação do NIF: 1 - Dispensado do NIF; 2 - Não exigência do NI" +
            "F;"))]
        [System.Xml.Serialization.XmlElementAttribute("cNaoNIF")]
        public TsCodNaoNif CNaoNif { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CNaoNif property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CNaoNifSpecified { get; set; }
        
        /// <summary>
        /// <para>Nome / Razão Social do do Fornecedor do serviço</para>
        /// <para xml:lang="en">Minimum length: 1.</para>
        /// <para xml:lang="en">Maximum length: 150.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Nome / Razão Social do do Fornecedor do serviço")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(1)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(150)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xNome")]
        public string XNome { get; set; }
    }
}
