//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TE205208", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Te205208
    {
        
        /// <summary>
        /// <para>Descrição do evento: "Anulação da Rejeição".</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Descrição do evento: \"Anulação da Rejeição\".")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("xDesc")]
        public Te205208XDesc XDesc { get; set; }
        
        /// <summary>
        /// <para>Informações do evento de anulação de rejeição da NFS-e.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Informações do evento de anulação de rejeição da NFS-e.")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("infAnRej")]
        public TcInfoEventoAnulacaoRejeicao InfAnRej { get; set; }
    }
}
