//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TE305103", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Te305103
    {
        
        /// <summary>
        /// <para>Descrição do evento: "Desbloqueio de NFS-e por Ofício".</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Descrição do evento: \"Desbloqueio de NFS-e por Ofício\".")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("xDesc")]
        public Te305103XDesc XDesc { get; set; }
        
        /// <summary>
        /// <para>CPF do agente da administração tributária municipal que efetuou o cancelamento por ofício de NFS-e.</para>
        /// <para>Tipo Número do CPF</para>
        /// <para xml:lang="en">Maximum length: 11.</para>
        /// <para xml:lang="en">Pattern: [0-9]{11}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("CPF do agente da administração tributária municipal que efetuou o cancelamento po" +
            "r ofício de NFS-e."))]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{11}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CPFAgTrib")]
        public string CpfAgTrib { get; set; }
        
        /// <summary>
        /// <para>Referência ao Id da "Manifestação de rejeição da NFS-e" que originou o presente evento de anulação.</para>
        /// <para>Referência ao Id "Manifestação de rejeição da NFS-e" que originou o presente evento de anulação.</para>
        /// <para xml:lang="en">Pattern: [0-9]{59}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Referência ao Id da \"Manifestação de rejeição da NFS-e\" que originou o presente e" +
            "vento de anulação."))]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{59}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("idBloqOfic")]
        public string IdBloqOfic { get; set; }
    }
}
