//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TE305102", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Te305102
    {
        
        /// <summary>
        /// <para>Descrição do evento: "Bloqueio de NFS-e por Ofício".</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Descrição do evento: \"Bloqueio de NFS-e por Ofício\".")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("xDesc")]
        public Te305102XDesc XDesc { get; set; }
        
        /// <summary>
        /// <para>CPF do agente da administração tributária municipal que efetuou o cancelamento por ofício de NFS-e.</para>
        /// <para>Tipo Número do CPF</para>
        /// <para xml:lang="en">Maximum length: 11.</para>
        /// <para xml:lang="en">Pattern: [0-9]{11}.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("CPF do agente da administração tributária municipal que efetuou o cancelamento po" +
            "r ofício de NFS-e."))]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(11)]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("[0-9]{11}")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CPFAgTrib")]
        public string CpfAgTrib { get; set; }
        
        /// <summary>
        /// <para>Descrição para explicitar o motivo indicado neste evento</para>
        /// <para>Descrição do motivo da substituição da NFS-e</para>
        /// <para xml:lang="en">Minimum length: 15.</para>
        /// <para xml:lang="en">Maximum length: 255.</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Descrição para explicitar o motivo indicado neste evento")]
        [System.ComponentModel.DataAnnotations.MinLengthAttribute(15)]
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(255)]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=false)]
        [System.Xml.Serialization.XmlElementAttribute("xMotivo")]
        public string XMotivo { get; set; }
        
        /// <summary>
        /// <para>Descrição para explicitar o motivo indicado neste evento</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Descrição para explicitar o motivo indicado neste evento")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("codEvento")]
        public TsCodigoEventoNfSe CodEvento { get; set; }
    }
}
