//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    /// <summary>
    /// <para>Categorias de veículos para cobrança:
    ///        00 - Categoria de veículos (tipo não informado na nota de origem)
    ///        01 - Automóvel, caminhonete e furgão;
    ///        02 - Caminhão leve, ônibus, caminhão trator e furgão;
    ///        03 - Automóvel e caminhonete com semireboque;
    ///        04 - Caminhão, caminhão-trator, caminhão-trator com semi-reboque e ônibus;
    ///        05 - Automóvel e caminhonete com reboque;
    ///        06 - Caminhão com reboque;
    ///        07 - Caminhão trator com semi-reboque;
    ///        08 - Motocicletas, motonetas e bicicletas motorizadas;
    ///        09 - Veículo especial;
    ///        10 - Veículo Isento;</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"Categorias de veículos para cobrança: 00 - Categoria de veículos (tipo não informado na nota de origem) 01 - Automóvel, caminhonete e furgão; 02 - Caminhão leve, ônibus, caminhão trator e furgão; 03 - Automóvel e caminhonete com semireboque; 04 - Caminhão, caminhão-trator, caminhão-trator com semi-reboque e ônibus; 05 - Automóvel e caminhonete com reboque; 06 - Caminhão com reboque; 07 - Caminhão trator com semi-reboque; 08 - Motocicletas, motonetas e bicicletas motorizadas; 09 - Veículo especial; 10 - Veículo Isento;")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TSCategVeic", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public enum TsCategVeic
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("00")]
        Item00,
        
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
        
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,
        
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,
        
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,
        
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,
        
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,
        
        [System.Xml.Serialization.XmlEnumAttribute("09")]
        Item09,
        
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
    }
}
