//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    /// <summary>
    /// <para>Código de evento da NFS-e
    ///      e101101 - Cancelamento de NFS-e;
    ///      e105102 - Cancelamento de NFS-e por Substituição;
    ///      e105104 - Cancelamento de NFS-e Deferido por Análise Fiscal;
    ///      e105105 - Cancelamento de NFS-e Indeferido por Análise Fiscal;
    ///      e305101 - Cancelamento de NFS-e por Ofício;
    ///      e907202 - ???????????????????????????????
    ///      e967203 - Tributos de NFS-e Recolhidos;</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"Código de evento da NFS-e e101101 - Cancelamento de NFS-e; e105102 - Cancelamento de NFS-e por Substituição; e105104 - Cancelamento de NFS-e Deferido por Análise Fiscal; e105105 - Cancelamento de NFS-e Indeferido por Análise Fiscal; e305101 - Cancelamento de NFS-e por Ofício; e907202 - ??????????????????????????????? e967203 - Tributos de NFS-e Recolhidos;")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TSCodigoEventoNFSe", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public enum TsCodigoEventoNfSe
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("e101101")]
        E101101,
        
        [System.Xml.Serialization.XmlEnumAttribute("e105102")]
        E105102,
        
        [System.Xml.Serialization.XmlEnumAttribute("e105104")]
        E105104,
        
        [System.Xml.Serialization.XmlEnumAttribute("e105105")]
        E105105,
        
        [System.Xml.Serialization.XmlEnumAttribute("e305101")]
        E305101,
        
        [System.Xml.Serialization.XmlEnumAttribute("e967203")]
        E967203,
    }
}
