//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    /// <summary>
    /// <para>Compartilhar as informações da NFS-e gerada a partir desta DPS com a Secretaria de Comércio Exterior:
    ///        0 - Não enviar para o MDIC;
    ///        1 - Enviar para o MDIC;</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Compartilhar as informações da NFS-e gerada a partir desta DPS com a Secretaria d" +
        "e Comércio Exterior: 0 - Não enviar para o MDIC; 1 - Enviar para o MDIC;"))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TSEnvMDIC", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public enum TsEnvMdic
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
}
