//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    /// <summary>
    /// <para>Mecanismo de apoio/fomento ao Comércio Exterior utilizado pelo tomador do serviço:
    ///00 - Desconhecido (tipo não informado na nota de origem);
    ///01 - Nenhum;
    ///02 - Adm. Pública e Repr. Internacional;
    ///03 - Alugueis e Arrend. Mercantil de maquinas, equip., embarc. e aeronaves;
    ///04 - Arrendamento Mercantil de aeronave para empresa de transporte aéreo público;
    ///05 - Comissão a agentes externos na exportação;
    ///06 - Despesas de armazenagem, mov. e transporte de carga no exterior;
    ///07 - Eventos FIFA (subsidiária);
    ///08 - Eventos FIFA;
    ///09 - Fretes, arrendamentos de embarcações ou aeronaves e outros;
    ///10 - Material Aeronáutico;
    ///11 - Promoção de Bens no Exterior;
    ///12 - Promoção de Dest. Turísticos Brasileiros;
    ///13 - Promoção do Brasil no Exterior;
    ///14 - Promoção Serviços no Exterior;
    ///15 - RECINE;
    ///16 - RECOPA;
    ///17 - Registro e Manutenção de marcas, patentes e cultivares;
    ///18 - REICOMP;
    ///19 - REIDI;
    ///20 - REPENEC;
    ///21 - REPES;
    ///22 - RETAERO; 
    ///23 - RETID;
    ///24 - Royalties, Assistência Técnica, Científica e Assemelhados;
    ///25 - Serviços de avaliação da conformidade vinculados aos Acordos da OMC;
    ///26 - ZPE;</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(@"Mecanismo de apoio/fomento ao Comércio Exterior utilizado pelo tomador do serviço: 00 - Desconhecido (tipo não informado na nota de origem); 01 - Nenhum; 02 - Adm. Pública e Repr. Internacional; 03 - Alugueis e Arrend. Mercantil de maquinas, equip., embarc. e aeronaves; 04 - Arrendamento Mercantil de aeronave para empresa de transporte aéreo público; 05 - Comissão a agentes externos na exportação; 06 - Despesas de armazenagem, mov. e transporte de carga no exterior; 07 - Eventos FIFA (subsidiária); 08 - Eventos FIFA; 09 - Fretes, arrendamentos de embarcações ou aeronaves e outros; 10 - Material Aeronáutico; 11 - Promoção de Bens no Exterior; 12 - Promoção de Dest. Turísticos Brasileiros; 13 - Promoção do Brasil no Exterior; 14 - Promoção Serviços no Exterior; 15 - RECINE; 16 - RECOPA; 17 - Registro e Manutenção de marcas, patentes e cultivares; 18 - REICOMP; 19 - REIDI; 20 - REPENEC; 21 - REPES; 22 - RETAERO; 23 - RETID; 24 - Royalties, Assistência Técnica, Científica e Assemelhados; 25 - Serviços de avaliação da conformidade vinculados aos Acordos da OMC; 26 - ZPE;")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TSMecAFComExToma", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public enum TsMecAfComExToma
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("00")]
        Item00,
        
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
        
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,
        
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,
        
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,
        
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,
        
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,
        
        [System.Xml.Serialization.XmlEnumAttribute("09")]
        Item09,
        
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
        
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,
        
        [System.Xml.Serialization.XmlEnumAttribute("17")]
        Item17,
        
        [System.Xml.Serialization.XmlEnumAttribute("18")]
        Item18,
        
        [System.Xml.Serialization.XmlEnumAttribute("19")]
        Item19,
        
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        
        [System.Xml.Serialization.XmlEnumAttribute("21")]
        Item21,
        
        [System.Xml.Serialization.XmlEnumAttribute("22")]
        Item22,
        
        [System.Xml.Serialization.XmlEnumAttribute("23")]
        Item23,
        
        [System.Xml.Serialization.XmlEnumAttribute("24")]
        Item24,
        
        [System.Xml.Serialization.XmlEnumAttribute("25")]
        Item25,
        
        [System.Xml.Serialization.XmlEnumAttribute("26")]
        Item26,
    }
}
