//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    /// <summary>
    /// <para>Tipo de ente governamental
    ///        Para administração pública direta e suas autarquias e fundações:
    ///        1 - União;
    ///        2 - Estado;
    ///        3 - Distrito Federal;
    ///        4 - Município;</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Tipo de ente governamental Para administração pública direta e suas autarquias e " +
        "fundações: 1 - União; 2 - Estado; 3 - Distrito Federal; 4 - Município;"))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TSRTCTpEnteGov", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public enum TsrtcTpEnteGov
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
}
