//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1188.0 using the following command:
// xscgen -n http://www.sped.fazenda.gov.br/nfse=Abrasf.Core.Models -n http://www.w3.org/2000/09/xmldsig#=Abrasf.Core.Models --dmb --sf -o ../../../Abrasf.Core/Models/NacionalTypesGenerated schema_v101.xsd
namespace NotaNacional.Core.Models
{
    
    
    /// <summary>
    /// <para>Tipo de emissão da NFS-e:
    ///        1 - Emissão normal no modelo da NFS-e Nacional;
    ///        2 - Emissão original em leiaute próprio do município com transcrição para o modelo da NFS-e Nacional.</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute(("Tipo de emissão da NFS-e: 1 - Emissão normal no modelo da NFS-e Nacional; 2 - Emi" +
        "ssão original em leiaute próprio do município com transcrição para o modelo da N" +
        "FS-e Nacional."))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1188.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TSTipoEmissao", Namespace="http://www.sped.fazenda.gov.br/nfse")]
    public enum TsTipoEmissao
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
}
